### ISSUE TITLE
Entourage failes in exported mode

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1]
I got it to start but it fails now with the following error message, related to either a view name or a icon path. Didn't have time to investigate further.

```
INFO: org.caleydo.core.view.ViewManager@7407f74e: Registering view: org.caleydo.view.pathway.GLPathway@3a1
Error: org.caleydo.core.util.exception.ExceptionHandler@79cc8b5a: Caught Exception: nulljava.lang.NullPointerException
        at org.eclipse.core.internal.runtime.Activator.getURLConverter(Activator.java:321)
        at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:205)
        at org.caleydo.core.view.ViewManager.getRemotePlugInViewIcon(ViewManager.java:773)
        at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer.addPluginVisualization(MultiFormRenderer.java:292)
        at org.caleydo.view.subgraph.GLSubGraph.createMultiformRenderer(GLSubGraph.java:613)
        at org.caleydo.view.subgraph.GLSubGraph.addPathway(GLSubGraph.java:565)
        at org.caleydo.view.subgraph.ranking.RankingElement.rowSelected(RankingElement.java:218)
        at org.caleydo.view.subgraph.ranking.RankingElement$1.propertyChange(RankingElement.java:73)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at org.caleydo.vis.rank.model.RankTableModel.setSelectedRow(RankTableModel.java:194)
        at org.caleydo.vis.rank.ui.TableBodyUI$3.pick(TableBodyUI.java:153)
        at org.caleydo.core.view.opengl.picking.PickingListenerComposite.pick(PickingListenerComposite.java:43)
        at org.caleydo.core.view.opengl.canvas.AGLView.notifyPickingListener(AGLView.java:693)
        at org.caleydo.core.view.opengl.canvas.AGLView.handlePicking(AGLView.java:685)
        at org.caleydo.core.view.opengl.canvas.AGLView.checkForHits(AGLView.java:640)
        at org.caleydo.core.view.opengl.layout2.AGLElementGLView.display(AGLElementGLView.java:144)
        at org.caleydo.view.subgraph.GLSubGraph.display(GLSubGraph.java:779)
        at org.caleydo.core.view.opengl.layout2.AGLElementGLView.displayLocal(AGLElementGLView.java:166)
        at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:367)
        at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
        at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
        at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:137)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
        at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:148)
        at jogamp.opengl.GLWorkerThread$WorkerRunnable.run(GLWorkerThread.java:259)
        at java.lang.Thread.run(Thread.java:722)

INFO: Subgraph view: Disposing view
```

**Comment by alexsb** [comment]
Prevented it from crashing everything by improving exception handling in bab669287ae2200e30ed99718846723d6b13653d

Source is still unsolved though.

**Comment by sgratzl** [comment]
fix: missing exported icons in enroute build.properties
