### ISSUE TITLE
GLSandbox under Mac

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1056]
at nils notebook 

```
[20:44:57] Caleydo Nils Gehlenborg: Exception in thread "main" javax.media.opengl.GLException: Create texture ID invalid: texID 0, glerr 0x0
 at com.jogamp.opengl.util.texture.Texture.validateTexID(Texture.java:1073)
 at com.jogamp.opengl.util.texture.Texture.updateImage(Texture.java:440)
 at com.jogamp.opengl.util.texture.Texture.updateImage(Texture.java:417)
 at com.jogamp.opengl.util.texture.Texture.<init>(Texture.java:182)
 at com.jogamp.opengl.util.texture.TextureIO.newTexture(TextureIO.java:447)
 at com.jogamp.opengl.util.texture.TextureIO.newTexture(TextureIO.java:431)
 at org.caleydo.data.loader.ResourceLoader.getTexture(ResourceLoader.java:95)
 at org.caleydo.core.view.opengl.util.texture.TextureManager.get(TextureManager.java:90)
 at org.caleydo.core.view.opengl.layout2.GLGraphics.getTexture(GLGraphics.java:321)
 at org.caleydo.core.view.opengl.layout2.GLGraphics.fillImage(GLGraphics.java:317)
 at org.caleydo.vis.rank.ui.TableUI$1.render(TableUI.java:73)
 at org.caleydo.core.view.opengl.layout2.GLElement.renderImpl(GLElement.java:224)
 at org.caleydo.core.view.opengl.layout2.basic.GLButton.renderImpl(GLButton.java:176)
 at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:203)
 at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:246)
 at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:203)
 at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:246)
 at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:203)
 at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:246)
 at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:203)
 at org.caleydo.core.view.opengl.layout2.GLSandBox.display(GLSandBox.java:272)
 at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
 at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
 at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
 at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
 at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:137)
 at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
 at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
 at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:148)
 at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:159)
 at com.jogamp.nativewindow.swt.SWTAccessor.invoke(SWTAccessor.java:306)
 at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:656)
 at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:375)
 at com.jogamp.opengl.swt.GLCanvas$8.paintControl(GLCanvas.java:306)
 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4134)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
 at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1244)
 at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:167)
 at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:741)
 at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:162)
 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5471)
 at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
 at org.eclipse.swt.internal.cocoa.NSWindow.makeKeyAndOrderFront(NSWindow.java:202)
 at org.eclipse.swt.widgets.Shell.makeKeyAndOrderFront(Shell.java:1278)
 at org.eclipse.swt.widgets.Shell.setWindowVisible(Shell.java:1953)
 at org.eclipse.swt.widgets.Shell.open(Shell.java:1336)
 at org.caleydo.core.view.opengl.layout2.GLSandBox.run(GLSandBox.java:320)
 at university.University.main(University.java:179)
[20:45:14] Caleydo Nils Gehlenborg: und das hier ist der andere:
[20:45:15] Caleydo Nils Gehlenborg: 2013-03-13 15:44:38.594 java[13116:707] _createMenuRef called with existing principal MenuRef already associated with menu
2013-03-13 15:44:38.596 java[13116:707] (
 0   CoreFoundation                      0x00007fff8743ff56 __exceptionPreprocess + 198
 1   libobjc.A.dylib                     0x00007fff93ffad5e objc_exception_throw + 43
 2   CoreFoundation                      0x00007fff8743fd8a +[NSException raise:format:arguments(inlove) + 106
 3   CoreFoundation                      0x00007fff8743fd14 +[NSException raise:format(inlove) + 116
 4   AppKit                              0x00007fff8b65294b -[NSCarbonMenuImpl _createMenuRef] + 64
 5   AppKit                              0x00007fff8b652236 -[NSCarbonMenuImpl _instantiateCarbonMenu] + 148
 6   AppKit                              0x00007fff8b626ecf -[NSApplication finishLaunching] + 878
 7   libswt-pi-cocoa-4234.jnilib         0x00000008dff15a5e Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSendSuper__Lorg_eclipse_swt_internal_cocoa_objc_1super_2J + 89
 8   ???                                 0x0000000108181fb0 0x0 + 4430766000
)
```

**Comment by sgratzl** [comment]
@ngehlenborg 

can you try it again, at my mac it works more or less.

I don't know why but: 
- three icons are not shown
- the context (clear color,...) must be initialized at every frame
- at the beginning I see nothing, but when I resize the window a bit everything will be drawn

**Comment by sgratzl** [comment]
r6208, r6209

as an alternative I created a s small RCP application -> start the org.caleydo.vis.rank as an RCP application, with all the demos as views

**Comment by sgratzl** [comment]
Replying to [comment:2 gratzl]:

> r6208, r6209
> 
> as an alternative I created a s small RCP application -> start the org.caleydo.vis.rank as an RCP application, with all the demos as views
> rcp works under mac

but to the sandbox: \
 I don't know why, but it seems that the three icons are sharing the same texture id with the one used by the text renderer. The result is that the paper basket to the right, shows the text cache

**Comment by alexsb** [comment]
Is that still a problem?

**Comment by sgratzl** [comment]
> Is that still a problem? 

I think the problem still exists, but is has no priority at all, as the sandbox is useful just for prototyping new simple techniques.

**Comment by sgratzl** [comment]
works for me with latest jogl
