### ISSUE TITLE
Entourage crashes with NPE on updatePathLinks()

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1100]
Not totally easy to reproduce, but is related to context operations  with paths maybe. 

!ENTRY org.caleydo.core.util.exception.ExceptionHandler@5628f181 4 0 2013-03-24 20:52:52.004
!MESSAGE Caught Exception: null
!STACK 0
java.lang.NullPointerException
    at org.caleydo.datadomain.pathway.graph.PathwayPath.getPathway(PathwayPath.java:67)
    at org.caleydo.view.subgraph.GLSubGraph.updatePathLinks(GLSubGraph.java:697)
    at org.caleydo.view.subgraph.GLSubGraph.updateAugmentation(GLSubGraph.java:717)
    at org.caleydo.view.subgraph.GLSubGraph.display(GLSubGraph.java:750)
    at org.caleydo.core.view.opengl.picking.PickingManager.handlePicking(PickingManager.java:405)
    at org.caleydo.core.view.opengl.layout2.AGLElementGLView.displayLocal(AGLElementGLView.java:175)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:367)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)

**Comment by dkalkofen** [comment]
- since i couldn't figure out why this function is still in the system i commented it out 
  => i keep the ticket open for a while in case i missed any side effects
