### ISSUE TITLE
ArrayIndexOutOfBoundsException after multiple path selections in L2 view

### ISSUE THREAD

**Issue by dkalkofen** [Caleydo/caleydo#1123]
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at org.caleydo.view.enroute.path.FixedPathUpdateStrategy$PathSelectionPickingListener.mouseOver(FixedPathUpdateStrategy.java:170)
    at org.caleydo.core.view.opengl.picking.APickingListener.pick(APickingListener.java:48)
    at org.caleydo.core.view.opengl.canvas.AGLView.notifyPickingListener(AGLView.java:693)
    at org.caleydo.core.view.opengl.canvas.AGLView.handlePicking(AGLView.java:685)
    at org.caleydo.core.view.opengl.canvas.AGLView.checkForHits(AGLView.java:640)

**Comment by cpartl** [comment]
can't reproduce that -> closing
