### ISSUE TITLE
StratomeX crashes when adding copy number column from Tour Guide

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1159]
To reproduce:
1. GBM data from March 22
2. Select mRNA 4 cluster CNMF column 
3. add first mRNA and then copy number in Tour Guide
4. select first copy number hit (1/2-SBSRNA4)

Exception:

``` java
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@60e34f0a 4 0 2013-04-29 08:37:13.204
!MESSAGE Caught Exception: null
!STACK 0
java.lang.NullPointerException
    at org.caleydo.view.stratomex.brick.ui.OverviewHeatMapRenderer.<init>(OverviewHeatMapRenderer.java:68)
    at org.caleydo.view.stratomex.brick.configurer.CategoricalDataConfigurer.setBrickViews(CategoricalDataConfigurer.java:158)
    at org.caleydo.view.stratomex.brick.GLBrick.initialize(GLBrick.java:304)
    at org.caleydo.view.stratomex.column.BrickColumn.createBrick(BrickColumn.java:471)
    at org.caleydo.view.stratomex.column.BrickColumn.createClusterBricks(BrickColumn.java:345)
    at org.caleydo.view.stratomex.column.BrickColumn.createBricks(BrickColumn.java:326)
    at org.caleydo.view.stratomex.column.BrickColumn.initRemote(BrickColumn.java:607)
    at org.caleydo.view.stratomex.GLStratomex.display(GLStratomex.java:504)
    at org.caleydo.view.stratomex.GLStratomex.displayLocal(GLStratomex.java:476)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:361)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
...
```

**Comment by alexsb** [comment]
This seems to work now. I tried it (with the latest project) and no problem.
