### ISSUE TITLE
concurrent modification exception in DVI when adding "mutation" to Tour Guide search space

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1166]
To reproduce:
1. run Jaccard index query on a data type that is not "mutation"
2. add mutation to the search space

``` java
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@57f9fb85 4 0 2013-04-29 09:00:34.572
!MESSAGE Caught Exception: null
!STACK 0
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
    at java.util.HashMap$KeyIterator.next(HashMap.java:928)
    at org.caleydo.view.dvi.node.TableBasedDataNode.retrieveTablePerspectives(TableBasedDataNode.java:427)
    at org.caleydo.view.dvi.node.TableBasedDataNode.update(TableBasedDataNode.java:339)
    at org.caleydo.view.dvi.GLDataViewIntegrator.updateDataDomain(GLDataViewIntegrator.java:665)
    at org.caleydo.view.dvi.listener.DataDomainChangedListener.handleEvent(DataDomainChangedListener.java:33)
    at org.caleydo.core.view.opengl.canvas.AGLView.processEvents(AGLView.java:509)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:313)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:137)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:148)
...
```

**Comment by sgratzl** [comment]
should not longer happen as the table perspectives are created on the fly and within the gl render thread
