### ISSUE TITLE
StratomeX crashes when right-clicking on column header of newly added column

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1170]
To reproduce:
1. run JI query on mRNA column (4 cluster CNMF in GBM)
2. add mRNA-seq and methylation to search space and remove mRNA
3. select mRNA-seq 2 cluster CNMF in mRNA-seq and add permanently to view using "+" button
4. try to right-click on header brick of 2 cluster CNMF mRNA-seq column

``` java

!ENTRY org.caleydo.core.util.exception.ExceptionHandler@4e745d25 4 0 2013-04-29 09:31:44.353
!MESSAGE Caught Exception: null
!STACK 0
java.lang.NullPointerException
    at org.caleydo.view.tourguide.api.score.AReferenceGroupScore.<init>(AReferenceGroupScore.java:39)
    at org.caleydo.view.tourguide.api.score.DefaultComputedReferenceGroupScore.<init>(DefaultComputedReferenceGroupScore.java:38)
    at org.caleydo.view.tourguide.impl.JaccardIndexScoreFactory.createJaccard(JaccardIndexScoreFactory.java:54)
    at org.caleydo.view.tourguide.impl.JaccardIndexScoreFactory.createGroupEntries(JaccardIndexScoreFactory.java:65)
    at org.caleydo.view.tourguide.internal.score.ScoreFactories.createGroupEntries(ScoreFactories.java:57)
    at org.caleydo.view.tourguide.internal.score.BrickContextMenuFactory.createGroupEntries(BrickContextMenuFactory.java:51)
    at org.caleydo.view.stratomex.brick.GLBrick$2.rightClicked(GLBrick.java:877)
    at org.caleydo.core.view.opengl.picking.APickingListener.pick(APickingListener.java:51)
    at org.caleydo.core.view.opengl.canvas.AGLView.notifyPickingListener(AGLView.java:687)
    at org.caleydo.core.view.opengl.canvas.AGLView.handlePicking(AGLView.java:679)
    at org.caleydo.core.view.opengl.canvas.AGLView.checkForHits(AGLView.java:634)
    at org.caleydo.view.stratomex.GLStratomex.displayLocal(GLStratomex.java:479)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:361)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:124)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:102)
...
```

**Comment by sgratzl** [comment]
invalid because of #1201
