### ISSUE TITLE
Show empty table before data is loaded in importer

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1240]
Currently only one header cell is shown.

**Comment by alexsb** [comment]
I see some columns and rows, but no cells?

**Comment by alexsb** [comment]
Observed on Linux, not observed on Windows 7

![no_cell](https://f.cloud.github.com/assets/2039375/612123/59582c34-cde6-11e2-9fe5-35b72c0080c9.png)

**Comment by alexsb** [comment]
Here's the exception:

java.lang.NullPointerException
    at org.eclipse.nebula.widgets.nattable.painter.cell.ColumnHeaderCheckBoxPainter.convertDataType(ColumnHeaderCheckBoxPainter.java:103)
    at org.eclipse.nebula.widgets.nattable.painter.cell.ColumnHeaderCheckBoxPainter.isChecked(ColumnHeaderCheckBoxPainter.java:99)
    at org.eclipse.nebula.widgets.nattable.painter.cell.ColumnHeaderCheckBoxPainter.getCheckedCellsCount(ColumnHeaderCheckBoxPainter.java:91)
    at org.eclipse.nebula.widgets.nattable.painter.cell.ColumnHeaderCheckBoxPainter.getImage(ColumnHeaderCheckBoxPainter.java:73)
    at org.eclipse.nebula.widgets.nattable.painter.cell.ImagePainter.getPreferredWidth(ImagePainter.java:45)
    at org.eclipse.nebula.widgets.nattable.painter.cell.decorator.CellPainterDecorator.getBaseCellPainterBounds(CellPainterDecorator.java:125)
    at org.eclipse.nebula.widgets.nattable.painter.cell.decorator.CellPainterDecorator.paintCell(CellPainterDecorator.java:106)
    at org.eclipse.nebula.widgets.nattable.painter.cell.CellPainterWrapper.paintCell(CellPainterWrapper.java:61)
    at org.eclipse.nebula.widgets.nattable.painter.cell.decorator.BeveledBorderDecorator.paintCell(BeveledBorderDecorator.java:70)
    at org.eclipse.nebula.widgets.nattable.painter.layer.CellLayerPainter.paintCell(CellLayerPainter.java:69)
    at org.eclipse.nebula.widgets.nattable.painter.layer.CellLayerPainter.paintLayer(CellLayerPainter.java:41)
    at org.eclipse.nebula.widgets.nattable.layer.CompositeLayer$CompositeLayerPainter.paintLayer(CompositeLayer.java:916)
    at org.eclipse.nebula.widgets.nattable.painter.layer.NatLayerPainter.paintLayer(NatLayerPainter.java:36)
    at org.eclipse.nebula.widgets.nattable.NatTable.paintNatTable(NatTable.java:333)
    at org.eclipse.nebula.widgets.nattable.NatTable.paintControl(NatTable.java:329)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1300)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1285)
    at org.eclipse.swt.widgets.Control.gtk_expose_event(Control.java:2992)
    at org.eclipse.swt.widgets.Composite.gtk_expose_event(Composite.java:709)
    at org.eclipse.swt.widgets.Canvas.gtk_expose_event(Canvas.java:167)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1769)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5116)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4377)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8317)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1193)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2342)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3184)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.caleydo.core.io.gui.ImportDataAction.run(ImportDataAction.java:47)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:452)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3186)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.caleydo.core.internal.Application.start(Application.java:87)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Error while painting table: null
