### ISSUE TITLE
Resize/update problem with category import interface.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1260]
The table containing the category details is not correctly sized initially, see screenshot.

![category_size](https://f.cloud.github.com/assets/2039375/638107/04e9c37e-d2b4-11e2-9b40-c8261cf8328f.png)

Here's the exception:

at org.eclipse.nebula.widgets.nattable.viewport.ViewportLayer.handleGridResize(ViewportLayer.java:725)
    at org.eclipse.nebula.widgets.nattable.viewport.ViewportLayer.doCommand(ViewportLayer.java:665)
    at org.eclipse.nebula.widgets.nattable.grid.layer.GridLayer.doCommandOnChildLayer(GridLayer.java:109)
    at org.eclipse.nebula.widgets.nattable.grid.layer.GridLayer.doCommandOnChildLayers(GridLayer.java:96)
    at org.eclipse.nebula.widgets.nattable.layer.CompositeLayer.doCommand(CompositeLayer.java:137)
    at org.eclipse.nebula.widgets.nattable.grid.layer.GridLayer.doCommand(GridLayer.java:178)
    at org.eclipse.nebula.widgets.nattable.NatTable.doCommand(NatTable.java:516)
    at org.eclipse.nebula.widgets.nattable.NatTable$4.handleEvent(NatTable.java:311)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1300)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1281)
    at org.eclipse.swt.widgets.ScrollBar.setVisible(ScrollBar.java:868)

Also, this exception seems to not be logged.

**Comment by cpartl** [comment]
Does this issue still exist? Can't reproduce it.

**Comment by alexsb** [comment]
No.
