### ISSUE TITLE
double-clicking entry in LineUp when in stratomeX insertion mode throws exception

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1342]
The insertion template disappears.

``` java

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.caleydo.core.event.EventListenerManager$AnnotationBasedEventListener.handleEvent(EventListenerManager.java:298)
    at org.caleydo.core.view.opengl.canvas.AGLView.processEvents(AGLView.java:513)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:314)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas.fireDisplay(SWTGLCanvas.java:132)
    at org.caleydo.core.view.opengl.canvas.internal.swt.SWTGLCanvas$2.display(SWTGLCanvas.java:105)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:137)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:148)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:4875)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5241)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3615)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.caleydo.core.internal.Application.start(Application.java:91)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.caleydo.view.stratomex.tourguide.TourguideAdapter.replaceTemplate(TourguideAdapter.java:771)
    at org.caleydo.view.stratomex.tourguide.TourguideAdapter.replacePathwayTemplate(TourguideAdapter.java:869)
    at org.caleydo.view.tourguide.internal.stratomex.AddWizardElement.replacePathwayTemplate(AddWizardElement.java:357)
    at org.caleydo.view.tourguide.api.state.BrowsePathwayState.onUpdate(BrowsePathwayState.java:47)
    at org.caleydo.view.tourguide.internal.stratomex.AddWizardElement.onUpdate(AddWizardElement.java:256)
    at org.caleydo.view.stratomex.tourguide.TourguideAdapter.onUpdatePreview(TourguideAdapter.java:698)
    ... 43 more
java.lang.reflect.InvocationTargetException
```

**Comment by sgratzl** [comment]
part of 0c3bef4478851421ea213e16841c3a496a2ca779
