### ISSUE TITLE
Juno Deserialization Problems

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1382]
Might be solved with Kepler, but I get the follwoing exception ATM:

```
!ENTRY org.eclipse.ui 4 0 2013-07-02 22:24:09.137
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Illegal secondary id (cannot be empty or contain a colon))
    at org.eclipse.swt.SWT.error(SWT.java:4361)
    at org.eclipse.swt.SWT.error(SWT.java:4276)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.caleydo.core.internal.Application.start(Application.java:77)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.IllegalArgumentException: Illegal secondary id (cannot be empty or contain a colon)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3735)
    at org.caleydo.core.view.ViewManager$1.run(ViewManager.java:825)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at 

org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    ... 24 more

```

Also, Lineup turns up twice:

![double_lineup](https://f.cloud.github.com/assets/2039375/740795/5073efe2-e388-11e2-9435-efd36da421a6.png)

To test use this project: 

Dropbox/Caleydo/projects/caleydo-project_2013.07.02_19.05.cal

**Comment by sgratzl** [comment]
Juno releated, can't fix it -> solved with Kepler

**Comment by sgratzl** [comment]
I can try to convert the multiple LineUp instance to three independent once, but that doesn't solve the StratomeX issues

-> Kepler

**Comment by mstreit** [comment]
@sgratzl Tell us when we should all switch to Kepler

**Comment by sgratzl** [comment]
I'm already working with Kepler, so three hours ago?

**Comment by mstreit** [comment]
OK, then we can close this issue.

**Comment by mstreit** [comment]
But the needed changes for Kepler are not yet merged to the develop branch. I have compile errors.
