### ISSUE TITLE
Crash when adding stratification to StratomeX via LineUp

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1431]
I had this error a couple of times in the last half hour. 
Reproduce with the following steps:
- Load Dropbox/Caleydo/projects/3.0/BRCA/*.cal project
- Add stratification with log-rank sign. via wizard
- Remove methylation and add mutation data in LineUp
- Click on first item in list
- Click on second item in list
  -> CRASH

```
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@4e134064 4 0 2013-07-09 14:32:09.033
!MESSAGE Caught Exception: null
!STACK 0
java.lang.NullPointerException
    at org.caleydo.view.stratomex.column.BrickColumn.addSortedBricks(BrickColumn.java:393)
    at org.caleydo.view.stratomex.column.BrickColumn.createClusterBricks(BrickColumn.java:374)
```

**Comment by mstreit** [comment]
works for me
