### ISSUE TITLE
Exception when parsing full matrix Methylation file

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1439]
Starting TCGA importer with:  -t GBM 2013_05_23 -g false

```
!ENTRY TabularDataParser: Methylation 4 0 2013-07-11 09:42:08.547
!MESSAGE Could not read data file.
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: 2
    at org.caleydo.core.io.parser.ascii.TabularDataParser.initializTables(TabularDataParser.java:233)
    at org.caleydo.core.io.parser.ascii.TabularDataParser.parseFile(TabularDataParser.java:246)
    at org.caleydo.core.io.parser.ascii.ATextParser.loadData(ATextParser.java:121)
    at org.caleydo.core.data.collection.table.TableUtils.loadData(TableUtils.java:104)
    at org.caleydo.core.io.DataLoader.loadDataSet(DataLoader.java:146)
    at org.caleydo.core.io.DataLoader.loadData(DataLoader.java:71)
    at org.caleydo.data.importer.tcga.ATCGATask.loadProject(ATCGATask.java:124)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:71)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:1)
    at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.regular.TCGARunTask.compute(TCGARunTask.java:47)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.AProjectBuilderApplication$1.compute(AProjectBuilderApplication.java:79)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
    at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:784)
    at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398)

!ENTRY DataLoader 4 0 2013-07-11 09:42:08.550
!MESSAGE Failed to load data for dataset Methylation
!STACK 0
java.lang.IllegalStateException: Could not read data file '/home/streit/git/caleydo/org.caleydo.data.importer/./tmp/20130523/GBM/gdac.broadinstitute.org_GBM-TP.Methylation_Clustering_CNMF.Level_4.2013052300.0.0.tar.gz/outputprefix.expclu.gct'
    at org.caleydo.core.io.parser.ascii.ATextParser.loadData(ATextParser.java:128)
    at org.caleydo.core.data.collection.table.TableUtils.loadData(TableUtils.java:104)
    at org.caleydo.core.io.DataLoader.loadDataSet(DataLoader.java:146)
    at org.caleydo.core.io.DataLoader.loadData(DataLoader.java:71)
    at org.caleydo.data.importer.tcga.ATCGATask.loadProject(ATCGATask.java:124)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:71)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:1)
    at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.regular.TCGARunTask.compute(TCGARunTask.java:47)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.AProjectBuilderApplication$1.compute(AProjectBuilderApplication.java:79)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
    at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:784)
    at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
    at org.caleydo.core.io.parser.ascii.TabularDataParser.initializTables(TabularDataParser.java:233)
    at org.caleydo.core.io.parser.ascii.TabularDataParser.parseFile(TabularDataParser.java:246)
    at org.caleydo.core.io.parser.ascii.ATextParser.loadData(ATextParser.java:121)
    ... 20 more

!ENTRY org.eclipse.osgi 4 0 2013-07-11 09:42:08.599
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:536)
    at java.util.concurrent.ForkJoinTask.reportResult(ForkJoinTask.java:596)
    at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:640)
    at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:1521)
    at org.caleydo.data.importer.tcga.AProjectBuilderApplication.generateTCGAProjectFiles(AProjectBuilderApplication.java:84)
    at org.caleydo.data.importer.tcga.AProjectBuilderApplication.start(AProjectBuilderApplication.java:37)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.NullPointerException
    at org.caleydo.core.io.DataLoader.loadRecordGroupings(DataLoader.java:228)
    at org.caleydo.core.io.DataLoader.loadGroupings(DataLoader.java:176)
    at org.caleydo.core.io.DataLoader.loadData(DataLoader.java:72)
    at org.caleydo.data.importer.tcga.ATCGATask.loadProject(ATCGATask.java:124)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:71)
    at org.caleydo.data.importer.tcga.regular.TCGATask.compute(TCGATask.java:1)
    at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.regular.TCGARunTask.compute(TCGARunTask.java:47)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:377)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:778)
    at org.caleydo.data.importer.tcga.AProjectBuilderApplication$1.compute(AProjectBuilderApplication.java:79)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:177)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
    at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:784)
    at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398)
An error has occurred. See the log file
/home/streit/caleydo/runtime-org.caleydo.data.importer.tcga.product/.metadata/.log.
```

**Comment by mstreit** [comment]
see #1216

**Comment by sgratzl** [comment]
should be fixed
