### ISSUE TITLE
GSEA results in OutOfMemoryException for full matrices

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1442]
```
!ENTRY org.eclipse.core.jobs 4 2 2013-07-11 15:12:40.637
!MESSAGE An internal error occurred during: "Compute LineUp Scores".
!STACK 0
java.lang.OutOfMemoryError: Java heap space
    at java.lang.Float.valueOf(Float.java:434)
    at org.caleydo.core.data.collection.table.Table.getNormalizedValue(Table.java:178)
    at org.caleydo.view.tourguide.impl.algorithm.GSEAAlgorithm.rankedSet(GSEAAlgorithm.java:114)
    at org.caleydo.view.tourguide.impl.algorithm.GSEAAlgorithm.init(GSEAAlgorithm.java:73)
    at org.caleydo.view.tourguide.internal.compute.ComputeStratificationJob.run(ComputeStratificationJob.java:57)
    at org.caleydo.view.tourguide.internal.compute.AComputeJob.runImpl(AComputeJob.java:103)
    at org.caleydo.view.tourguide.internal.compute.ComputeAllOfJob.run(ComputeAllOfJob.java:56)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.ui 4 0 2013-07-11 15:12:40.645
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: Java heap space
    at org.eclipse.swt.widgets.Control.gtk_enter_notify_event(Control.java:3042)
    at org.eclipse.swt.widgets.Shell.gtk_enter_notify_event(Shell.java:1234)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2083)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5467)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4569)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8707)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1243)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2287)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3361)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.caleydo.core.internal.Application.start(Application.java:84)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
Exception in thread "[Timer] - Main Queue Handler" java.lang.OutOfMemoryError: Java heap space
    at org.eclipse.equinox.internal.util.impl.tpt.threadpool.ThreadPoolFactoryImpl.execute0(ThreadPoolFactoryImpl.java:94)
    at org.eclipse.equinox.internal.util.impl.tpt.timer.TimerImpl.run(TimerImpl.java:110)
    at java.lang.Thread.run(Thread.java:722)
Exception in thread "main-null-Timer0" java.lang.OutOfMemoryError: Java heap space
    at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1119)
    at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:241)
    at java.awt.Font.createGlyphVector(Font.java:2532)
    at org.caleydo.core.view.opengl.util.text.MyTextRenderer$DefaultRenderDelegate.getBounds(MyTextRenderer.java:1171)
    at org.caleydo.core.view.opengl.util.text.MyTextRenderer.getBounds(MyTextRenderer.java:327)
    at org.caleydo.core.view.opengl.util.text.CaleydoTextRenderer.getRequiredTextWidth(CaleydoTextRenderer.java:260)
    at org.caleydo.core.view.opengl.util.text.CompositeTextRenderer.getTextWidth(CompositeTextRenderer.java:65)
    at org.caleydo.core.view.opengl.layout2.GLGraphics.drawText(GLGraphics.java:486)
    at org.caleydo.core.view.opengl.layout2.GLGraphics.drawText(GLGraphics.java:460)
    at org.caleydo.core.view.opengl.layout2.GLGraphics.drawText(GLGraphics.java:451)
    at org.caleydo.vis.rank.model.GroupRankColumnModel.render(GroupRankColumnModel.java:123)
    at org.caleydo.vis.rank.ui.column.AColumnHeaderUI.renderBackground(AColumnHeaderUI.java:333)
    at org.caleydo.vis.rank.ui.column.AColumnHeaderUI.renderImpl(AColumnHeaderUI.java:263)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.vis.rank.ui.column.SimpleColumnHeaderUI.renderBaseImpl(SimpleColumnHeaderUI.java:168)
    at org.caleydo.vis.rank.ui.column.SimpleColumnHeaderUI.renderImpl(SimpleColumnHeaderUI.java:158)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.vis.rank.ui.TableHeaderUI.renderImpl(TableHeaderUI.java:132)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.vis.rank.ui.TableUI.renderImpl(TableUI.java:63)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.basic.ScrollingDecorator.doRender(ScrollingDecorator.java:194)
    at org.caleydo.core.view.opengl.layout2.basic.ScrollingDecorator.renderImpl(ScrollingDecorator.java:137)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:264)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:194)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:224)
```

**Comment by sgratzl** [comment]
I don't think that I'm able to fix this as the nature of GSEA is time and memory consuming -> #1195

**Comment by sgratzl** [comment]
I added again the PGSEA as alternative to the GSEA to the wizard, you may give it a try

**Comment by mstreit** [comment]
ok
