### ISSUE TITLE
out of memory when trying to load large matrices

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1459]
When trying to load a matrix with ~20K rows and ~500 columns (all floats) I got an out of memory error (see below).

A test file is in the Dropbox (projects > 3.0 > KIRC > KIRC.uncv1.mRNAseq_RPKM.txt -unzip before use).

``` java
Error while logging event loop exception:
java.lang.OutOfMemoryError: Java heap space
    at java.lang.String.substring(String.java:1913)
    at java.lang.String.split(String.java:2288)
    at java.lang.String.split(String.java:2355)
    at org.caleydo.core.io.gui.dataimport.FilePreviewParser.parse(FilePreviewParser.java:82)
    at org.caleydo.core.io.gui.dataimport.wizard.LoadDataSetPageMediator.createDataPreviewTableFromFile(LoadDataSetPageMediator.java:623)
    at org.caleydo.core.io.gui.dataimport.wizard.LoadDataSetPageMediator.initWidgets(LoadDataSetPageMediator.java:252)
    at org.caleydo.core.io.gui.dataimport.wizard.LoadDataSetPageMediator.onSelectFile(LoadDataSetPageMediator.java:165)
    at org.caleydo.core.io.gui.dataimport.wizard.LoadDataSetPage$1.on(LoadDataSetPage.java:204)
    at org.caleydo.core.io.gui.dataimport.wizard.LoadDataSetPage$1.on(LoadDataSetPage.java:1)
    at org.caleydo.core.io.gui.dataimport.widget.LoadFileWidget.onOpenFile(LoadFileWidget.java:65)
    at org.caleydo.core.io.gui.dataimport.widget.LoadFileWidget$1.widgetSelected(LoadFileWidget.java:42)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1474)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4012)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3651)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
    at org.eclipse.jface.window.Window.open(Window.java:802)
    at org.caleydo.core.io.gui.ImportDataHandler.execute(ImportDataHandler.java:22)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
Logging exception:
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.Arrays.copyOfRange(Arrays.java:2694)
    at java.lang.String.<init>(String.java:203)
    at java.lang.StringBuilder.toString(StringBuilder.java:405)
    at java.lang.StackTraceElement.toString(StackTraceElement.java:172)
    at java.lang.String.valueOf(String.java:2854)
    at java.lang.StringBuilder.append(StringBuilder.java:128)
    at java.lang.Throwable.printStackTrace(Throwable.java:657)
    at java.lang.Throwable.printStackTrace(Throwable.java:720)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLogWriter.getStackTrace(EclipseLogWriter.java:424)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLogWriter.writeStack(EclipseLogWriter.java:515)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLogWriter.writeLog(EclipseLogWriter.java:458)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLogWriter.log(EclipseLogWriter.java:281)
    at org.eclipse.core.runtime.internal.adaptor.EclipseLogWriter.logged(EclipseLogWriter.java:694)
    at org.eclipse.equinox.log.internal.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:86)
    at org.eclipse.equinox.log.internal.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:205)
    at org.eclipse.equinox.log.internal.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:178)
    at org.eclipse.equinox.log.internal.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:65)
    at org.eclipse.equinox.log.internal.ExtendedLogServiceImpl.log(ExtendedLogServiceImpl.java:87)
    at org.eclipse.equinox.log.internal.LoggerImpl.log(LoggerImpl.java:54)
    at org.eclipse.core.internal.runtime.Log.log(Log.java:62)
    at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:830)
    at org.eclipse.ui.statushandlers.StatusManager.logError(StatusManager.java:280)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:201)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:242)
    at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(WorkbenchAdvisor.java:326)
    at org.eclipse.ui.internal.ExceptionHandler.handleException(ExceptionHandler.java:65)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:830)
    at org.eclipse.jface.window.Window.open(Window.java:802)
    at org.caleydo.core.io.gui.ImportDataHandler.execute(ImportDataHandler.java:22)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)

!ENTRY org.eclipse.ui 4 0 2013-07-12 16:42:26.954
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: GC overhead limit exceeded

!ENTRY org.eclipse.ui 4 0 2013-07-12 16:44:02.452
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: GC overhead limit exceeded

!ENTRY org.eclipse.ui 4 0 2013-07-12 16:44:11.672
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by mstreit** [comment]
Works for me. Should be no problem when using 2GB heap space.
