### ISSUE TITLE
out of memory after querying for copy number stratifications

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1480]
Used the BRCA case study data set. This happened when I queried for copy number data the second time (I had queried and previewed some pathways earlier in the session).

``` java
!ENTRY org.caleydo.view.tourguide.internal.compute.ComputeAllOfJob 1 0 2013-07-14 20:46:40.622
!MESSAGE compute the data for datadomain: Copy Number
done in 3.550 ms

!ENTRY org.caleydo.view.tourguide.internal.compute.ComputeScoreJob 1 0 2013-07-14 20:46:40.741
!MESSAGE computing group similarity of 90922 against 1 group scores, 0 group metrics, 0 stratification scores and 0 stratification metrics
done in 87.16 ms

!ENTRY IDType 1 0 2013-07-14 20:46:48.935
!MESSAGE Registering IDType tree_1716961581
Exception in thread "main-null-Timer0" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2219)
    at java.util.ArrayList.grow(ArrayList.java:213)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:187)
    at java.util.ArrayList.add(ArrayList.java:411)
    at org.caleydo.core.data.collection.Histogram.add(Histogram.java:84)
    at org.caleydo.core.data.collection.CategoricalHistogram.add(CategoricalHistogram.java:41)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.calculateHistogram(TablePerspectiveStatistics.java:198)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.getHistogram(TablePerspectiveStatistics.java:136)
    at org.caleydo.view.histogram.GLHistogram.renderHistogram(GLHistogram.java:197)
    at org.caleydo.view.histogram.GLHistogram.buildDisplayList(GLHistogram.java:180)
    at org.caleydo.view.histogram.GLHistogram.display(GLHistogram.java:158)
    at org.caleydo.view.histogram.GLHistogram.displayLocal(GLHistogram.java:142)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:371)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:583)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:567)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1029)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:904)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at com.jogamp.opengl.util.DefaultAnimatorImpl.display(DefaultAnimatorImpl.java:50)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:440)
    at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:167)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

**Comment by sgratzl** [comment]
I can't really do anything against Memory Errors except of: increasing your local maximum Heap space: `-Xmx4g` 

or do a big refactoring that is about memory optimization: see #955, #1455,
