### ISSUE TITLE
KEGG pathway parsing error

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1503]
pathway: hsa05205

```
!STACK 0
java.lang.NumberFormatException: For input string: "5578＋mmu:18750"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:492)
    at java.lang.Integer.valueOf(Integer.java:582)
    at org.caleydo.datadomain.pathway.parser.KgmlSaxHandler.handleEntryTag(KgmlSaxHandler.java:250)
    at org.caleydo.datadomain.pathway.parser.KgmlSaxHandler.startElement(KgmlSaxHandler.java:109)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:506)
    at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2717)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
    at org.caleydo.datadomain.pathway.parser.KEGGParser.parse(KEGGParser.java:150)
    at org.caleydo.datadomain.pathway.PathwayDataDomain.run(PathwayDataDomain.java:136)
    at java.lang.Thread.run(Thread.java:724)
```

could you please take a look at it and check if any side effect will appear (e.g. that we are skipping one or more pathways

**Comment by mstreit** [comment]
This is a bug in the pathway itself. The "＋mmu:18750" needs to be removed. I did this in the local version. As we load the pathways directly from KEGG, we need to handle this in the parser.
