### ISSUE TITLE
selecting "self-sampled" matrices cause exception in histogram view

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1531]
``` java
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@5526c08b 4 0 2013-08-12 12:55:24.999
!MESSAGE Caught Exception: Index: 29, Size: 29
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 29, Size: 29
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.caleydo.core.data.collection.Histogram.add(Histogram.java:96)
    at org.caleydo.core.data.collection.Histogram.addNAN(Histogram.java:104)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.calculateHistogram(TablePerspectiveStatistics.java:222)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.getHistogram(TablePerspectiveStatistics.java:142)
    at org.caleydo.view.histogram.GLHistogram.renderHistogram(GLHistogram.java:195)
    at org.caleydo.view.histogram.GLHistogram.buildDisplayList(GLHistogram.java:178)
    at org.caleydo.view.histogram.GLHistogram.display(GLHistogram.java:156)
    at org.caleydo.view.histogram.GLHistogram.displayLocal(GLHistogram.java:140)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:389)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:583)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:567)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1029)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:904)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.displayIfNoAnimatorNoCheck(GLCanvas.java:559)
    at com.jogamp.opengl.swt.GLCanvas.access$1100(GLCanvas.java:88)
    at com.jogamp.opengl.swt.GLCanvas$7.handleEvent(GLCanvas.java:362)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1474)
    at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1244)
    at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:166)
    at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:749)
    at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:161)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5534)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:4918)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5296)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.caleydo.core.internal.Application.start(Application.java:86)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```

**Comment by ngehlenborg** [comment]
Kaputt repariert. Now there is a different but related bug:

``` java

!ENTRY org.caleydo.core.util.exception.ExceptionHandler@32474395 4 0 2013-08-12 14:38:27.337
!MESSAGE Caught Exception: Index: 5, Size: 0
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.caleydo.core.data.collection.Histogram.add(Histogram.java:96)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.calculateHistogram(TablePerspectiveStatistics.java:231)
    at org.caleydo.core.data.perspective.table.TablePerspectiveStatistics.getHistogram(TablePerspectiveStatistics.java:142)
    at org.caleydo.view.histogram.GLHistogram.renderHistogram(GLHistogram.java:195)
    at org.caleydo.view.histogram.GLHistogram.buildDisplayList(GLHistogram.java:178)
    at org.caleydo.view.histogram.GLHistogram.display(GLHistogram.java:156)
    at org.caleydo.view.histogram.GLHistogram.displayLocal(GLHistogram.java:140)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:389)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:583)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:567)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1029)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:904)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.displayIfNoAnimatorNoCheck(GLCanvas.java:559)
    at com.jogamp.opengl.swt.GLCanvas.access$1100(GLCanvas.java:88)
    at com.jogamp.opengl.swt.GLCanvas$7.handleEvent(GLCanvas.java:362)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1474)
    at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1244)
    at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:166)
    at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:749)
    at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:161)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5534)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:4918)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5296)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.caleydo.core.internal.Application.start(Application.java:86)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```
