### ISSUE TITLE
rendering freeze in LineUp

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1573]
The stratification LineUp view freezes and stops rendering. I have not been able to reproduce reliably yet, but it has happened twice already today. More to follow.

``` java
Error: org.caleydo.core.view.opengl.canvas.MyAnimator: display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5f87b6fc,
    handle    0x11d7271a0,
    Drawable size 2337x312,
    SWT size 2337x312]java.lang.NullPointerException
    at org.caleydo.vis.lineup.layout.UniformRowHeightLayout.layout(UniformRowHeightLayout.java:30)
    at org.caleydo.vis.lineup.ui.column.OrderColumnUI.layoutImpl(OrderColumnUI.java:163)
    at org.caleydo.core.view.opengl.layout2.GLElement.layout(GLElement.java:284)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.layout(AnimatedGLElementContainer.java:250)
    at org.caleydo.vis.lineup.ui.TableBodyUI.layout(TableBodyUI.java:465)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.AGLElementDecorator.layout(AGLElementDecorator.java:78)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.layoutPass(AGLElementView.java:237)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:191)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.display(GLTourGuideView.java:569)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by ngehlenborg** [comment]
Closing and re-openign the view helps.

**Comment by ngehlenborg** [comment]
This is somehow connected to inserting new columns using double-click in the LineUp view. I have tried this only with clinical data columns so far. After double-clicking one or two columns the view stops reacting to user input and after switching to another LineUp tab and back to the stratification tab, above error is throw over and over until I close the stratification tab.
