### ISSUE TITLE
Gene search is broken

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#159]
java.lang.NullPointerException
    at org.caleydo.core.manager.mapping.IDMappingManager.getID(IDMappingManager.java:256)
    at org.caleydo.core.view.swt.data.search.DataEntitySearcherViewRep.searchForGeneShortName(DataEntitySearcherViewRep.java:128)
    at org.caleydo.core.view.swt.data.search.DataEntitySearcherViewRep.searchForEntity(DataEntitySearcherViewRep.java:59)

**Comment by mstreit** [comment]
Gene search itself works.
But the gene is not selected in newly highlighted pathway after dynamic pathway loading.

**Comment by alexsb** [comment]
Gene search broken again.

**Comment by mstreit** [comment]
Fixed with newly implemented search view. Will not be fixed in stable version 1.1.
