### ISSUE TITLE
Entourage crash

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1595]
coming from #1594. 

Entourage crashed during startup: 

``` java
java.lang.NullPointerException
    at org.caleydo.core.data.datadomain.ATableBasedDataDomain.convertForeignPerspective(ATableBasedDataDomain.java:854)
    at org.caleydo.view.entourage.datamapping.DataMappingState.addTablePerspective(DataMappingState.java:71)
    at org.caleydo.view.entourage.datamapping.DataMappingState.addDataDomain(DataMappingState.java:66)
    at org.caleydo.view.entourage.datamapping.TableBasedDataDomainElement.onSelectionChanged(TableBasedDataDomainElement.java:51)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.fireCallback(GLButton.java:101)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.setSelected(GLButton.java:95)
    at org.caleydo.view.entourage.datamapping.GLExperimentalDataMapping.addDataDomainElements(GLExperimentalDataMapping.java:94)
    at org.caleydo.view.entourage.datamapping.GLExperimentalDataMapping.<init>(GLExperimentalDataMapping.java:74)
    at org.caleydo.view.entourage.GLEntourage.<init>(GLEntourage.java:150)
    at org.caleydo.view.entourage.RcpGLSubGraphView.createPartControl(RcpGLSubGraphView.java:55)
...
```

reproduce: just open Entourage within e.g. the KIRC project

**Comment by alexsb** [comment]
That's because Entourage is hacked to work only with the one CCLE project....

**Comment by cpartl** [comment]
I think this is fixed now.
