### ISSUE TITLE
StratomeX crashes when assigning numerical variable for KM plot

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1696]
I suspect that in my current data set this is caused by an ID that exists for the numerical variable but not in the stratification.

The error looks like this:

``` java
!ENTRY org.caleydo.view.tourguide.internal.compute.ComputeAllOfJob 1 0 2013-10-23 13:52:34.212
!MESSAGE compute the data for datadomain: Patient Table
done in 1.441 ms
add data of Patient Table

!ENTRY Patient Table 1 0 2013-10-23 13:52:37.638
!MESSAGE Failed to convert 1 elements when converting [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.genetic_-209bd52e-141e165e0d6--7fff_1183575776], size: 481] with size 481 for this data domain.

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.643
!MESSAGE Registering view: org.caleydo.view.stratomex.column.BrickColumn@1ccd005c

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.645
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 480]]
Register 483197022

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.654
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 134]]
Register 483197023

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.658
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 41]]
Register 483197024

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.662
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 186]]
Register 483197025

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.666
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 92]]
Register 483197026

!ENTRY org.caleydo.core.view.ViewManager@5cb680de 1 0 2013-10-23 13:52:37.670
!MESSAGE Registering view: Brick: [D: [P for [IDType of Patient Table_column: dimension_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 1]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.generic_12a0807f-141e663748f--7ff8_584699659], size: 27]]
Similarity size sum 134!= group sum 135

!ENTRY org.caleydo.core.util.exception.ExceptionHandler@7951b154 4 0 2013-10-23 13:52:37.688
!MESSAGE Caught Exception: 495
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: 495
    at org.caleydo.core.data.collection.column.container.FloatContainer.get(FloatContainer.java:76)
    at org.caleydo.core.data.collection.column.container.FloatContainer.get(FloatContainer.java:1)
    at org.caleydo.core.data.collection.column.AColumn.getRaw(AColumn.java:144)
    at org.caleydo.core.data.collection.table.Table.getRaw(Table.java:274)
    at org.caleydo.view.kaplanmeier.GLKaplanMeier.calculateMaxAxisTime(GLKaplanMeier.java:191)
    at org.caleydo.view.kaplanmeier.KaplanMeierRemoteViewCreator.createRemoteView(KaplanMeierRemoteViewCreator.java:50)
    at org.caleydo.core.view.ViewManager.createRemotePlugInView(ViewManager.java:572)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer$ViewInfo.create(MultiFormRenderer.java:217)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer$ViewInfo.setActive(MultiFormRenderer.java:197)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer.ensureValidRenderer(MultiFormRenderer.java:482)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer.setElementLayout(MultiFormRenderer.java:715)
    at org.caleydo.core.view.opengl.layout.ElementLayout.setRenderer(ElementLayout.java:448)
    at org.caleydo.view.stratomex.brick.layout.HeaderBrickLayoutTemplate.setStaticLayouts(HeaderBrickLayoutTemplate.java:163)
    at org.caleydo.core.view.opengl.layout.LayoutManager.setStaticLayoutConfiguration(LayoutManager.java:89)
    at org.caleydo.view.stratomex.brick.GLBrick.setBrickLayoutTemplate(GLBrick.java:707)
    at org.caleydo.view.stratomex.brick.GLBrick.init(GLBrick.java:318)
    at org.caleydo.view.stratomex.brick.GLBrick.initRemote(GLBrick.java:408)
    at org.caleydo.view.stratomex.column.BrickColumn.display(BrickColumn.java:684)
    at org.caleydo.view.stratomex.GLStratomex.display(GLStratomex.java:641)
    at org.caleydo.view.stratomex.GLStratomex.displayLocal(GLStratomex.java:511)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:389)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by alexsb** [comment]
The cause is a missing LF at the end of the file. In the parser we determine the number of lines and initialize an array based on that size. In cases with a LF at the end we have one line more than if there is no LF.
