### ISSUE TITLE
Exception when disabeling on-node mapping. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1743]
Can't reproduce at the moment, but should be easy to prevent. Will keep trying:

```
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@5883b87f 4 0 2013-11-26 11:09:34.209
!MESSAGE Caught Exception: Index: 0, Size: 0
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.createLayout(MappedDataRenderer.java:310)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.reBuildLayout(MappedDataRenderer.java:246)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.setLinearizedNodes(MappedDataRenderer.java:241)
    at org.caleydo.view.enroute.GLEnRoutePathway.updateLayout(GLEnRoutePathway.java:366)
    at org.caleydo.view.enroute.GLEnRoutePathway.display(GLEnRoutePathway.java:291)
    at org.caleydo.view.enroute.GLEnRoutePathway.displayRemote(GLEnRoutePathway.java:271)
    at org.caleydo.core.view.opengl.layout.util.ViewLayoutRenderer.renderContent(ViewLayoutRenderer.java:89)
    at org.caleydo.core.view.opengl.layout.AForwardingRenderer.renderContent(AForwardingRenderer.java:63)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer.renderContent(MultiFormRenderer.java:661)
    at org.caleydo.core.view.opengl.layout.ALayoutRenderer.render(ALayoutRenderer.java:98)
    at org.caleydo.core.view.opengl.layout.ElementLayout.render(ElementLayout.java:652)
    at org.caleydo.core.view.opengl.layout.LayoutManager.render(LayoutManager.java:127)
    at org.caleydo.core.view.opengl.layout2.GLElementAdapter.renderAdapter(GLElementAdapter.java:152)
    at org.caleydo.view.entourage.ScrollableGLElementAdapter.renderImpl(ScrollableGLElementAdapter.java:185)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:199)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:199)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
```

**Comment by alexsb** [comment]
Duplicate of #1757
