### ISSUE TITLE
Exception when enabling new dataset while contextual data is in abstract mode?

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1758]
I can't provide a clear path to reproduce, but It's something with a the box plot of a contextual dataset and switching to a copy number stratification, possibly with an empty group. I can produce it 40% of the time after trying, but can't quite pin it down. 

```
!ENTRY org.caleydo.core.util.exception.ExceptionHandler@1c144c78 4 0 2013-11-27 17:01:26.206
!MESSAGE Caught Exception: -1
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: -1
    at org.caleydo.core.util.function.AdvancedDoubleStatistics.median(AdvancedDoubleStatistics.java:117)
    at org.caleydo.core.util.function.AdvancedDoubleStatistics.ofImpl(AdvancedDoubleStatistics.java:76)
    at org.caleydo.core.util.function.AdvancedDoubleStatistics.of(AdvancedDoubleStatistics.java:68)
    at org.caleydo.view.enroute.mappeddataview.AMedianBasedSummaryRenderer.<init>(AMedianBasedSummaryRenderer.java:60)
    at org.caleydo.view.enroute.mappeddataview.SummaryBoxAndWhiskersRenderer.<init>(SummaryBoxAndWhiskersRenderer.java:26)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.prepareData(MappedDataRenderer.java:816)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.createLayout(MappedDataRenderer.java:583)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.reBuildLayout(MappedDataRenderer.java:252)
    at org.caleydo.view.enroute.mappeddataview.MappedDataRenderer.setLinearizedNodes(MappedDataRenderer.java:246)
    at org.caleydo.view.enroute.GLEnRoutePathway.updateLayout(GLEnRoutePathway.java:366)
    at org.caleydo.view.enroute.GLEnRoutePathway.display(GLEnRoutePathway.java:291)
    at org.caleydo.view.enroute.GLEnRoutePathway.displayRemote(GLEnRoutePathway.java:271)
    at org.caleydo.core.view.opengl.layout.util.ViewLayoutRenderer.renderContent(ViewLayoutRenderer.java:89)
    at org.caleydo.core.view.opengl.layout.AForwardingRenderer.renderContent(AForwardingRenderer.java:63)
    at org.caleydo.core.view.opengl.layout.util.multiform.MultiFormRenderer.renderContent(MultiFormRenderer.java:661)
    at org.caleydo.core.view.opengl.layout.ALayoutRenderer.render(ALayoutRenderer.java:98)
    at org.caleydo.core.view.opengl.layout.ElementLayout.render(ElementLayout.java:652)
    at org.caleydo.core.view.opengl.layout.LayoutManager.render(LayoutManager.java:127)
    at org.caleydo.core.view.opengl.layout2.GLElementAdapter.renderAdapter(GLElementAdapter.java:152)
    at org.caleydo.view.entourage.ScrollableGLElementAdapter.renderImpl(ScrollableGLElementAdapter.java:185)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.view.entourage.GLWindow.renderImpl(GLWindow.java:83)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.renderImpl(AnimatedGLElementContainer.java:492)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.renderImpl(AnimatedGLElementContainer.java:492)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:206)
    at org.caleydo.core.view.opengl.layout2.AGLElementGLView.display(AGLElementGLView.java:157)
    at org.caleydo.view.entourage.GLEntourage.display(GLEntourage.java:856)
    at org.caleydo.core.view.opengl.layout2.AGLElementGLView.displayLocal(AGLElementGLView.java:183)
    at org.caleydo.core.view.opengl.canvas.AGLView.display(AGLView.java:388)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by cpartl** [comment]
@alexsb couldn't reproduce it, but attempted to fix by handling empty groups, please check again

**Comment by alexsb** [comment]
Closing until it appears again.
