### ISSUE TITLE
Entourage failes to start on Windows 64 bit

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1768]
With this exception and the CCLE dataset:

```
java.lang.NullPointerException
    at org.caleydo.core.data.selection.SelectionManager.<init>(SelectionManager.java:93)
    at org.caleydo.core.data.selection.EventBasedSelectionManager.<init>(EventBasedSelectionManager.java:48)
    at org.caleydo.view.entourage.GLEntourage.<init>(GLEntourage.java:283)
    at org.caleydo.view.entourage.RcpGLEntourageView.createPartControl(RcpGLEntourageView.java:58)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:142)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:174)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:323)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:877)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:857)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:119)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:333)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:254)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:102)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:71)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:53)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:949)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:633)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$6.run(PartRenderingEngine.java:526)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:511)
    at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:61)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:949)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:633)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:735)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:706)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:700)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:685)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.createElement(PartServiceImpl.java:1076)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1038)
    at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1211)
    at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1176)
    at org.eclipse.ui.internal.WorkbenchPage$12.run(WorkbenchPage.java:4077)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4074)
    at org.caleydo.core.view.ViewManager$1.run(ViewManager.java:827)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.caleydo.core.internal.Application.start(Application.java:97)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426) 
```

**Comment by wassermai** [comment]
Das stand in der log Datei

```
INFO: org.caleydo.core.internal.Application: Starting Caleydo
OK: org.caleydo.core.internal.Application: Environment Variables:
=::=::\
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\AnneWassermann\AppData\Roaming
COMPUTERNAME=AWASSERMANNHOME
ComSpec=C:\Windows\system32\cmd.exe
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\AnneWassermann
LOCALAPPDATA=C:\Users\AnneWassermann\AppData\Local
LOGONSERVER=\\AWASSERMANNHOME
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
Path=C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Acer ProShield\;C:\Program Files\Acer ProShield\x86;C:\Program Files (x86)\NTRU Cryptosystems\NTRU TCG Software Stack\bin\;C:\Program Files\NTRU Cryptosystems\NTRU TCG Software Stack\bin\;C:\Users\AnneWassermann\AppData\Local\Smartbar\Application\;C:\Users\AnneWassermann\AppData\Local\Smartbar\Application\
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\ANNEWA~1\AppData\Local\Temp
TMP=C:\Users\ANNEWA~1\AppData\Local\Temp
USERDOMAIN=AWassermannHome
USERNAME=AnneWassermann
USERPROFILE=C:\Users\AnneWassermann
asl.log=Destination=file
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

OK: org.caleydo.core.internal.Application: System Properties:
awt.toolkit=sun.awt.windows.WToolkit
eclipse.application=org.caleydo.core.application
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
C:\Program Files\Caleydo\Caleydo.exe
-name
Caleydo
--launcher.library
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20130807-1835\eclipse_1503.dll
-startup
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
--launcher.overrideVmargs
-exitdata
71c_5c
-data
@noDefault
-vm
C:\Windows\system32\javaw.exe

eclipse.home.location=file:/C:/Program Files/Caleydo/
eclipse.launcher=C:\Program Files\Caleydo\Caleydo.exe
eclipse.launcher.name=Caleydo
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
eclipse.product=org.caleydo.core.product
eclipse.startTime=1386300354101
eclipse.vm=C:\Windows\system32\javaw.exe
eclipse.vmargs=-Xms512m
-Xmx2048m
-XX:MaxPermSize=256m
-Djava.util.logging.config.file=data/logging/logging.properties
-jar
C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar

equinox.use.ds=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
java.class.version=51.0
java.endorsed.dirs=C:\Program Files\Java\jre7\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre7\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre7
java.io.tmpdir=C:\Users\ANNEWA~1\AppData\Local\Temp\
java.library.path=C:\Windows\system32;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Acer ProShield\;C:\Program Files\Acer ProShield\x86;C:\Program Files (x86)\NTRU Cryptosystems\NTRU TCG Software Stack\bin\;C:\Program Files\NTRU Cryptosystems\NTRU TCG Software Stack\bin\;C:\Users\AnneWassermann\AppData\Local\Smartbar\Application\;C:\Users\AnneWassermann\AppData\Local\Smartbar\Application\;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.7.0_04-b20
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.7
java.util.logging.config.file=data/logging/logging.properties
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.7.0_04
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.7
java.vm.vendor=Oracle Corporation
java.vm.version=23.0-b21
line.separator=

org.eclipse.equinox.launcher.splash.handle=656840
org.eclipse.equinox.launcher.splash.location=E:\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.equinox.launcher\org.caleydo.core_3.1.1\splash.bmp
org.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.update.reconcile=false
org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2,JRE-1.1,J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JavaSE-1.6,JavaSE-1.7
org.osgi.framework.language=de
org.osgi.framework.os.name=Windows7
org.osgi.framework.os.version=6.1.0
org.osgi.framework.processor=x86-64
org.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2",osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1",osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7"
org.osgi.framework.system.packages=javax.accessibility,javax.activation,javax.activity,javax.annotation,javax.annotation.processing,javax.crypto,javax.crypto.interfaces,javax.crypto.spec,javax.imageio,javax.imageio.event,javax.imageio.metadata,javax.imageio.plugins.bmp,javax.imageio.plugins.jpeg,javax.imageio.spi,javax.imageio.stream,javax.jws,javax.jws.soap,javax.lang.model,javax.lang.model.element,javax.lang.model.type,javax.lang.model.util,javax.management,javax.management.loading,javax.management.modelmbean,javax.management.monitor,javax.management.openmbean,javax.management.relation,javax.management.remote,javax.management.remote.rmi,javax.management.timer,javax.naming,javax.naming.directory,javax.naming.event,javax.naming.ldap,javax.naming.spi,javax.net,javax.net.ssl,javax.print,javax.print.attribute,javax.print.attribute.standard,javax.print.event,javax.rmi,javax.rmi.CORBA,javax.rmi.ssl,javax.script,javax.security.auth,javax.security.auth.callback,javax.security.auth.kerberos,javax.security.auth.login,javax.security.auth.spi,javax.security.auth.x500,javax.security.cert,javax.security.sasl,javax.sound.midi,javax.sound.midi.spi,javax.sound.sampled,javax.sound.sampled.spi,javax.sql,javax.sql.rowset,javax.sql.rowset.serial,javax.sql.rowset.spi,javax.swing,javax.swing.border,javax.swing.colorchooser,javax.swing.event,javax.swing.filechooser,javax.swing.plaf,javax.swing.plaf.basic,javax.swing.plaf.metal,javax.swing.plaf.multi,javax.swing.plaf.nimbus,javax.swing.plaf.synth,javax.swing.table,javax.swing.text,javax.swing.text.html,javax.swing.text.html.parser,javax.swing.text.rtf,javax.swing.tree,javax.swing.undo,javax.tools,javax.transaction,javax.transaction.xa,javax.xml,javax.xml.bind,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.bind.helpers,javax.xml.bind.util,javax.xml.crypto,javax.xml.crypto.dom,javax.xml.crypto.dsig,javax.xml.crypto.dsig.dom,javax.xml.crypto.dsig.keyinfo,javax.xml.crypto.dsig.spec,javax.xml.datatype,javax.xml.namespace,javax.xml.parsers,javax.xml.soap,javax.xml.stream,javax.xml.stream.events,javax.xml.stream.util,javax.xml.transform,javax.xml.transform.dom,javax.xml.transform.sax,javax.xml.transform.stax,javax.xml.transform.stream,javax.xml.validation,javax.xml.ws,javax.xml.ws.handler,javax.xml.ws.handler.soap,javax.xml.ws.http,javax.xml.ws.soap,javax.xml.ws.spi,javax.xml.ws.spi.http,javax.xml.ws.wsaddressing,javax.xml.xpath,org.ietf.jgss,org.omg.CORBA,org.omg.CORBA_2_3,org.omg.CORBA_2_3.portable,org.omg.CORBA.DynAnyPackage,org.omg.CORBA.ORBPackage,org.omg.CORBA.portable,org.omg.CORBA.TypeCodePackage,org.omg.CosNaming,org.omg.CosNaming.NamingContextExtPackage,org.omg.CosNaming.NamingContextPackage,org.omg.Dynamic,org.omg.DynamicAny,org.omg.DynamicAny.DynAnyFactoryPackage,org.omg.DynamicAny.DynAnyPackage,org.omg.IOP,org.omg.IOP.CodecFactoryPackage,org.omg.IOP.CodecPackage,org.omg.Messaging,org.omg.PortableInterceptor,org.omg.PortableInterceptor.ORBInitInfoPackage,org.omg.PortableServer,org.omg.PortableServer.CurrentPackage,org.omg.PortableServer.POAManagerPackage,org.omg.PortableServer.POAPackage,org.omg.PortableServer.portable,org.omg.PortableServer.ServantLocatorPackage,org.omg.SendingContext,org.omg.stub.java.rmi,org.w3c.dom,org.w3c.dom.bootstrap,org.w3c.dom.css,org.w3c.dom.events,org.w3c.dom.html,org.w3c.dom.ls,org.w3c.dom.ranges,org.w3c.dom.stylesheets,org.w3c.dom.traversal,org.w3c.dom.views,org.w3c.dom.xpath,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers
org.osgi.framework.uuid=a0e4581d-265e-0013-13be-852cd72886fa
org.osgi.framework.vendor=Eclipse
org.osgi.framework.version=1.7.0
org.osgi.supports.framework.extension=true
org.osgi.supports.framework.fragment=true
org.osgi.supports.framework.requirebundle=true
os.arch=amd64
os.name=Windows 7
os.version=6.1
osgi.arch=x86_64
osgi.bundles=reference:file:org.eclipse.equinox.simpleconfigurator_1.0.400.v20130327-2119.jar@1:start
osgi.bundles.defaultStartLevel=4
osgi.bundlestore=E:\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.osgi\bundles
osgi.configuration.area=file:/E:/.eclipse/1542257127_win32_win32_x86_64/configuration/
osgi.framework=file:/c:/Program Files/Caleydo/plugins/org.eclipse.osgi_3.9.1.v20130814-1242.jar
osgi.framework.extensions=
osgi.framework.shape=jar
osgi.framework.version=3.9.1.v20130814-1242
osgi.install.area=file:/C:/Program Files/Caleydo/
osgi.logfile=E:\.eclipse\1542257127_win32_win32_x86_64\configuration\1386300354444.log
osgi.manifest.cache=E:\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.osgi\manifests
osgi.nl=de_DE
osgi.os=win32
osgi.sharedConfiguration.area=file:/c:/Program Files/Caleydo/configuration/
osgi.splashLocation=E:\.eclipse\1542257127_win32_win32_x86_64\configuration\org.eclipse.equinox.launcher\org.caleydo.core_3.1.1\splash.bmp
osgi.splashPath=platform:/base/plugins/org.caleydo.core
osgi.syspath=c:\Program Files\Caleydo\plugins
osgi.ws=win32
path.separator=;
sun.arch.data.model=64
sun.boot.class.path=C:\Program Files\Java\jre7\lib\resources.jar;C:\Program Files\Java\jre7\lib\rt.jar;C:\Program Files\Java\jre7\lib\sunrsasign.jar;C:\Program Files\Java\jre7\lib\jsse.jar;C:\Program Files\Java\jre7\lib\jce.jar;C:\Program Files\Java\jre7\lib\charsets.jar;C:\Program Files\Java\jre7\lib\jfr.jar;C:\Program Files\Java\jre7\classes
sun.boot.library.path=C:\Program Files\Java\jre7\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar -os win32 -ws win32 -arch x86_64 -showsplash -launcher C:\Program Files\Caleydo\Caleydo.exe -name Caleydo --launcher.library C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20130807-1835\eclipse_1503.dll -startup C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar --launcher.overrideVmargs -exitdata 71c_5c -data @noDefault -vm C:\Windows\system32\javaw.exe -vmargs -Xms512m -Xmx2048m -XX:MaxPermSize=256m -Djava.util.logging.config.file=data/logging/logging.properties -jar C:\Program Files\Caleydo\\plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=Service Pack 1
user.country=DE
user.dir=C:\Program Files\Caleydo
user.home=E:
user.language=de
user.name=AnneWassermann
user.script=
user.timezone=America/New_York
user.variant=

INFO: org.caleydo.core.internal.Application: creating wizard shell
INFO: org.caleydo.core.internal.Application: open wizard
INFO: org.caleydo.core.internal.Application: wizard done
INFO: org.caleydo.core.serialize.ProjectManager: Error Loading Workbench Data  from E:\.caleydo_3.1\temp_load\workbench.xmi
INFO: org.caleydo.datadomain.pathway.parser.KEGGParser: Start parsing KEGG pathways.
INFO: org.caleydo.datadomain.pathway.parser.KEGGParser: Finished parsing KEGG pathways.
INFO: org.caleydo.core.startup.LoadProjectStartupProcedure@556bb6ef: Load serialized project
WARNING: org.caleydo.core.serialize.ProjectManager: Error Loading Bundle : org.caleydo.lib.jogl
WARNING: org.caleydo.core.serialize.ProjectManager: Error Loading Bundle : org.caleydo.data.importer
Error: org.caleydo.core.serialize.ProjectManager: Error Loading Project from
E:\.caleydo_3.1\temp_load\java.lang.RuntimeException: Could not create JAXBContexts
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:68)
    at org.caleydo.core.serialize.SerializationManager.<init>(SerializationManager.java:59)
    at org.caleydo.core.serialize.SerializationManager.get(SerializationManager.java:76)
    at org.caleydo.core.manager.GeneralManager.getSerializationManager(GeneralManager.java:187)
    at org.caleydo.core.serialize.ProjectManager.loadData(ProjectManager.java:162)
    at org.caleydo.core.serialize.ProjectManager.loadProjectData(ProjectManager.java:116)
    at org.caleydo.core.startup.LoadProjectStartupProcedure.run(LoadProjectStartupProcedure.java:120)
    at org.caleydo.core.internal.Application$3.run(Application.java:243)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration does not have a no-arg default constructor.
    this problem is related to the following location:
        at org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration
        at public org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration org.caleydo.core.util.clusterer.initialization.ClusterConfiguration.getClusterAlgorithmConfiguration()
        at org.caleydo.core.util.clusterer.initialization.ClusterConfiguration
        at public java.util.ArrayList org.caleydo.core.io.DataProcessingDescription.getColumnClusterConfigurations()
        at org.caleydo.core.io.DataProcessingDescription
        at public org.caleydo.core.io.DataProcessingDescription org.caleydo.core.io.DataSetDescription.getDataProcessingDescription()
        at org.caleydo.core.io.DataSetDescription
        at public org.caleydo.core.io.DataSetDescription org.caleydo.core.data.datadomain.ADataDomain.getDataSetDescription()
        at org.caleydo.core.data.datadomain.ADataDomain
        at org.caleydo.core.data.datadomain.ATableBasedDataDomain
        at public org.caleydo.core.data.datadomain.ATableBasedDataDomain org.caleydo.core.serialize.DataDomainSerializationData.getDataDomain()
        at org.caleydo.core.serialize.DataDomainSerializationData

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(Unknown Source)
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.find(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:66)
    ... 8 more

INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@1afd2618: Registering view: org.caleydo.view.dvi.GLDataViewIntegrator@570001
INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core.view.ViewManager@1afd2618: Registering view: StratomeX
INFO: org.caleydo.core: Start animator
INFO: org.caleydo.core: Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]
INFO: org.caleydo.core: Stop animator
INFO: org.caleydo.core.serialize.ProjectManager: Saving Plugin Data
INFO: org.caleydo.core.serialize.ProjectManager: Saving Data
Error: org.caleydo.core.serialize.ProjectManager: Error Saving Auto-Save Projectjava.lang.RuntimeException: Could not create JAXBContexts
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:68)
    at org.caleydo.core.serialize.SerializationManager.<init>(SerializationManager.java:59)
    at org.caleydo.core.serialize.SerializationManager.get(SerializationManager.java:76)
    at org.caleydo.core.manager.GeneralManager.getSerializationManager(GeneralManager.java:187)
    at org.caleydo.core.serialize.ProjectManager.saveData(ProjectManager.java:442)
    at org.caleydo.core.serialize.ProjectManager.access$4(ProjectManager.java:439)
    at org.caleydo.core.serialize.ProjectManager$3.run(ProjectManager.java:395)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration does not have a no-arg default constructor.
    this problem is related to the following location:
        at org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration
        at public org.caleydo.core.util.clusterer.initialization.AClusterAlgorithmConfiguration org.caleydo.core.util.clusterer.initialization.ClusterConfiguration.getClusterAlgorithmConfiguration()
        at org.caleydo.core.util.clusterer.initialization.ClusterConfiguration
        at public java.util.ArrayList org.caleydo.core.io.DataProcessingDescription.getColumnClusterConfigurations()
        at org.caleydo.core.io.DataProcessingDescription
        at public org.caleydo.core.io.DataProcessingDescription org.caleydo.core.io.DataSetDescription.getDataProcessingDescription()
        at org.caleydo.core.io.DataSetDescription
        at public org.caleydo.core.io.DataSetDescription org.caleydo.core.data.datadomain.ADataDomain.getDataSetDescription()
        at org.caleydo.core.data.datadomain.ADataDomain
        at org.caleydo.core.data.datadomain.ATableBasedDataDomain
        at public org.caleydo.core.data.datadomain.ATableBasedDataDomain org.caleydo.core.serialize.DataDomainSerializationData.getDataDomain()
        at org.caleydo.core.serialize.DataDomainSerializationData

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(Unknown Source)
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
    at javax.xml.bind.ContextFinder.find(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
    at org.caleydo.core.serialize.SerializationManager.createNewProjectContext(SerializationManager.java:66)
    ... 7 more

INFO: org.caleydo.core.serialize.ProjectManager: Saved Recent Project
INFO: org.caleydo.core.internal.Application: Bye bye!
```

**Comment by alexsb** [comment]
Looks like this is the problem:

```
java.runtime.version=1.7.0_04-b20
```

The current version is 1.7.45, you are running version 4, so you're 41 versions behind ;). 

Java 7 was pretty buggy until the two-digit version numbers. Please update java - 

http://java.com/en/download/index.jsp

and let us know if it worked.

**Comment by alexsb** [comment]
Works.
