### ISSUE TITLE
Cannot add stratifications via DnD

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1794]
```
!ENTRY org.caleydo.view.tourguide.internal.compute.ComputeAllOfJob 1 0 2013-12-18 11:11:04.566
!MESSAGE compute the data for datadomain: mRNA
done in 965.0 μs
add data of mRNA
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.caleydo.core.event.EventListenerManager$AnnotationBasedEventListener.handleEvent(EventListenerManager.java:304)
    at org.caleydo.core.event.EventExecuteRunner.run(EventListenerManagers.java:166)
    at org.caleydo.core.event.EventListenerManagers$QueuedEventListenerManager.processEvents(EventListenerManagers.java:93)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:191)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at org.caleydo.view.domino.internal.ui.ANodeUI.getSize(ANodeUI.java:116)
    at org.caleydo.view.domino.internal.ui.ANodeElement.getNodeSize(ANodeElement.java:215)
    at org.caleydo.view.domino.internal.ui.ANodeElement.getPreferredSize(ANodeElement.java:256)
    at org.caleydo.view.domino.internal.ui.ANodeElement.<init>(ANodeElement.java:61)
    at org.caleydo.view.domino.internal.ui.NodeElement.<init>(NodeElement.java:44)
    at org.caleydo.view.domino.internal.ui.DominoNodeLayer.vertexAdded(DominoNodeLayer.java:141)
    at org.caleydo.view.domino.internal.ui.model.DominoGraph.vertexAdded(DominoGraph.java:352)
    at org.caleydo.view.domino.internal.ui.model.DominoGraph.addVertex(DominoGraph.java:342)
    at org.caleydo.view.domino.internal.ui.DominoBackgroundLayer.onDrop(DominoBackgroundLayer.java:80)
    at org.caleydo.core.view.opengl.layout2.internal.MouseLayer.onDropItemEvent(MouseLayer.java:370)
    ... 23 more
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.caleydo.core.event.EventListenerManager$AnnotationBasedEventListener.handleEvent(EventListenerManager.java:304)
    at org.caleydo.core.event.EventExecuteRunner.run(EventListenerManagers.java:166)
    at org.caleydo.core.event.EventListenerManagers$QueuedEventListenerManager.processEvents(EventListenerManagers.java:93)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:191)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at org.caleydo.view.domino.internal.ui.ANodeUI.getSize(ANodeUI.java:116)
    at org.caleydo.view.domino.internal.ui.ANodeElement.getNodeSize(ANodeElement.java:215)
    at org.caleydo.view.domino.internal.ui.ANodeElement.getPreferredSize(ANodeElement.java:256)
    at org.caleydo.view.domino.internal.ui.ANodeElement.<init>(ANodeElement.java:61)
    at org.caleydo.view.domino.internal.ui.NodeElement.<init>(NodeElement.java:44)
    at org.caleydo.view.domino.internal.ui.DominoNodeLayer.vertexAdded(DominoNodeLayer.java:141)
    at org.caleydo.view.domino.internal.ui.model.DominoGraph.vertexAdded(DominoGraph.java:352)
    at org.caleydo.view.domino.internal.ui.model.DominoGraph.addVertex(DominoGraph.java:342)
    at org.caleydo.view.domino.internal.ui.DominoBackgroundLayer.onDrop(DominoBackgroundLayer.java:80)
    at org.caleydo.core.view.opengl.layout2.internal.MouseLayer.onDropItemEvent(MouseLayer.java:370)
    ... 23 more
java.lang.reflect.InvocationTargetException
```

**Comment by sgratzl** [comment]
move to sgratzl/org.caleydo.view.domino#9
