### ISSUE TITLE
Copy Number & Mutation Status properties don't show up in  Startification LineUp

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1876]
The properties for categorical startifications are missing: 

![image](https://cloud.githubusercontent.com/assets/2039375/6253743/bbf6e648-b771-11e4-9db5-876c583fa51f.png)

There should be independent columns for mutated/not mutated, etc. 

Also, the categorical stratifications only show up after I deselect and select them again, here is a missing example: 

![image](https://cloud.githubusercontent.com/assets/2039375/6253774/e79c2682-b771-11e4-8bd4-8fa6ce70061c.png)

Given the state in this screenshot, I can make the mutation status appear by selecting copy number (which don't appear) and deselecting copy-number again. 

Platform: Mac
Dataset: Both sample TCGA 

Partial log:

```
Error: org.caleydo.core.view.opengl.canvas.MyAnimator: display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5230d60,
    handle    0x61000012a3c0,
    Drawable size 2267x343,
    SWT size 2267x343]javax.media.opengl.GLException: Caught NullPointerException: null on thread MyAnimator GL Thread
    at javax.media.opengl.GLException.newGLException(GLException.java:75)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:185)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.caleydo.view.tourguide.internal.view.col.CategoricalPercentageRankColumnModel.create(CategoricalPercentageRankColumnModel.java:56)
    at org.caleydo.view.tourguide.api.model.CategoricalDataDomainQuery.createSpecificColumns(CategoricalDataDomainQuery.java:230)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.onActiveChanged(GLTourGuideView.java:325)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView$1.propertyChange(GLTourGuideView.java:132)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at org.caleydo.view.tourguide.api.model.ADataDomainQuery.setActive(ADataDomainQuery.java:127)
    at org.caleydo.view.tourguide.internal.view.ui.ADataDomainElement.onSelectionChanged(ADataDomainElement.java:88)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.fireCallback(GLButton.java:114)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.setSelected(GLButton.java:95)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.onMouseReleased(GLButton.java:170)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement.onPicked(PickableGLElement.java:140)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement$1.pick(PickableGLElement.java:50)
    at org.caleydo.core.view.opengl.picking.PickingListenerComposite.pick(PickingListenerComposite.java:38)
    at org.caleydo.core.view.opengl.picking.SimplePickingManager$PickingEntry.fire(SimplePickingManager.java:27)
    at org.caleydo.core.view.opengl.picking.APickingEntry.fire(APickingEntry.java:66)
    at org.caleydo.core.view.opengl.picking.APickingManager.fireListeners(APickingManager.java:275)
    at org.caleydo.core.view.opengl.picking.APickingManager.doPicking(APickingManager.java:147)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.pickingPass(AGLElementView.java:276)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:211)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.display(GLTourGuideView.java:601)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:690)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:672)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
    ... 12 more

OK: org.caleydo.core.view.opengl.canvas.internal.DnDAdapter: SWTGLCanvas of SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5230d60,
    handle    0x61000012a3c0,
    Drawable size 2267x343,
    SWT size 2267x343]creating DragSource
OK: org.caleydo.core.view.opengl.canvas.internal.DnDAdapter: SWTGLCanvas of SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5230d60,
    handle    0x61000012a3c0,
    Drawable size 2267x343,
    SWT size 2267x343]creating DropTarget
Error: org.caleydo.core.view.opengl.canvas.MyAnimator: display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5230d60,
    handle    0x61000012a3c0,
    Drawable size 2267x343,
    SWT size 2267x343]javax.media.opengl.GLException: Caught NullPointerException: null on thread MyAnimator GL Thread
    at javax.media.opengl.GLException.newGLException(GLException.java:75)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:185)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.caleydo.view.tourguide.internal.view.col.CategoricalPercentageRankColumnModel.create(CategoricalPercentageRankColumnModel.java:56)
    at org.caleydo.view.tourguide.api.model.CategoricalDataDomainQuery.createSpecificColumns(CategoricalDataDomainQuery.java:230)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.onActiveChanged(GLTourGuideView.java:325)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView$1.propertyChange(GLTourGuideView.java:132)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at org.caleydo.view.tourguide.api.model.ADataDomainQuery.setActive(ADataDomainQuery.java:127)
    at org.caleydo.view.tourguide.internal.view.ui.ADataDomainElement.onSelectionChanged(ADataDomainElement.java:88)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.fireCallback(GLButton.java:114)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.setSelected(GLButton.java:95)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.onMouseReleased(GLButton.java:170)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement.onPicked(PickableGLElement.java:140)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement$1.pick(PickableGLElement.java:50)
    at org.caleydo.core.view.opengl.picking.PickingListenerComposite.pick(PickingListenerComposite.java:38)
    at org.caleydo.core.view.opengl.picking.SimplePickingManager$PickingEntry.fire(SimplePickingManager.java:27)
    at org.caleydo.core.view.opengl.picking.APickingEntry.fire(APickingEntry.java:66)
    at org.caleydo.core.view.opengl.picking.APickingManager.fireListeners(APickingManager.java:275)
    at org.caleydo.core.view.opengl.picking.APickingManager.doPicking(APickingManager.java:147)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.pickingPass(AGLElementView.java:276)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:211)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.display(GLTourGuideView.java:601)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:690)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:672)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
    ... 12 more

Error: org.caleydo.core.view.opengl.canvas.MyAnimator: display error: SWT-GLCanvas[Realized true,
    jogamp.opengl.macosx.cgl.MacOSXOnscreenCGLDrawable,
    Factory   jogamp.opengl.macosx.cgl.MacOSXCGLDrawableFactory@5230d60,
    handle    0x61000012a3c0,
    Drawable size 2267x343,
    SWT size 2267x343]javax.media.opengl.GLException: Caught NullPointerException: null on thread MyAnimator GL Thread
    at javax.media.opengl.GLException.newGLException(GLException.java:75)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:185)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.caleydo.view.tourguide.internal.view.col.CategoricalPercentageRankColumnModel.create(CategoricalPercentageRankColumnModel.java:56)
    at org.caleydo.view.tourguide.api.model.CategoricalDataDomainQuery.createSpecificColumns(CategoricalDataDomainQuery.java:230)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.onActiveChanged(GLTourGuideView.java:325)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView$1.propertyChange(GLTourGuideView.java:132)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at org.caleydo.view.tourguide.api.model.ADataDomainQuery.setActive(ADataDomainQuery.java:127)
    at org.caleydo.view.tourguide.internal.view.ui.ADataDomainElement.onSelectionChanged(ADataDomainElement.java:88)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.fireCallback(GLButton.java:114)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.setSelected(GLButton.java:95)
    at org.caleydo.core.view.opengl.layout2.basic.GLButton.onMouseReleased(GLButton.java:170)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement.onPicked(PickableGLElement.java:140)
    at org.caleydo.core.view.opengl.layout2.PickableGLElement$1.pick(PickableGLElement.java:50)
    at org.caleydo.core.view.opengl.picking.PickingListenerComposite.pick(PickingListenerComposite.java:38)
    at org.caleydo.core.view.opengl.picking.SimplePickingManager$PickingEntry.fire(SimplePickingManager.java:27)
    at org.caleydo.core.view.opengl.picking.APickingEntry.fire(APickingEntry.java:66)
    at org.caleydo.core.view.opengl.picking.APickingManager.fireListeners(APickingManager.java:275)
    at org.caleydo.core.view.opengl.picking.APickingManager.doPicking(APickingManager.java:147)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.pickingPass(AGLElementView.java:276)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:211)
    at org.caleydo.view.tourguide.internal.view.GLTourGuideView.display(GLTourGuideView.java:601)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:690)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:672)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
    ... 12 more
```

**Comment by sgratzl** [comment]
the problem was that somehow the JAXB derserialization changed, such that it will not set the list but just get it and fill it internally. The side effect was that the internal lookup cache within CategoricalClassDescriptions wasn't populated.
