### ISSUE TITLE
LineUp unable to process large doubles?

### ISSUE THREAD

**Issue by bradleybio** [Caleydo/caleydo#1877]
I have encountered problems with using LineUp when a column contains large numbers. Specifically, when I load this toy tab-delimited file:

```
geneName        deltaPsi        bayesFactor
MYH3    1       7.3e+15
GTF2IRD2        1       5.7e+11
KLHDC4  0.98    48
DIAPH1  0.97    1.1e+41
IVNS1ABP        0.9     7.5e+205

```

I find that the entries for DIAPH1 and IVNS1ABP are stripped out without warning. As best as I can tell, whether or not a row is stripped out depends upon its bayesFactor value. Strangely, when I replace the above toy example with a bigger file, I find that that MYH3 example from above also disappears, so it is as if the stripping out of rows somehow depends upon the distribution of bayesFactor values over the entire file.

As a possibly related but distinct issue, when I select one of the rows (e.g., for MYH3) that is successfully loaded by LineUp from the above toy example, no data is displayed for the bayesFactor column for that row.

I am using the stand-alone version of LineUp (downloaded this morning, 2/26/15). Here are the contents of the log file for opening this toy file:

```
!SESSION 2015-02-26 10:08:31.934 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/rbradley/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault -keyring /Users/rbradley/.eclipse_keyring -showlocation

!ENTRY org.eclipse.ui.workbench 4 2 2015-02-26 10:08:34.789
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
    at org.caleydo.core.startup.InteractiveSplashHandler.init(InteractiveSplashHandler.java:54)
    at org.eclipse.ui.internal.Workbench$6.run(Workbench.java:773)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:794)
    at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:712)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:590)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at demo.DemoApplication.start(DemoApplication.java:43)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

!ENTRY org.eclipse.ui 4 0 2015-02-26 10:08:34.802
!MESSAGE Could not instantiate splash
!STACK 0
java.lang.NullPointerException
    at org.caleydo.core.startup.InteractiveSplashHandler.init(InteractiveSplashHandler.java:54)
    at org.eclipse.ui.internal.Workbench$6.run(Workbench.java:773)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:794)
    at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:712)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:590)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at demo.DemoApplication.start(DemoApplication.java:43)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

!ENTRY org.eclipse.ui 4 0 2015-02-26 10:08:34.816
!MESSAGE Error occurred during status handling
!STACK 0
java.lang.NullPointerException
    at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.<init>(StatusHandlerRegistry.java:72)
    at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.getDefault(StatusHandlerRegistry.java:91)
    at org.eclipse.ui.statushandlers.StatusManager.getStatusHandler(StatusManager.java:135)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:189)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:242)
    at org.eclipse.ui.internal.Workbench$6.handleException(Workbench.java:784)
    at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:75)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:44)
    at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:794)
    at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:712)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:590)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at demo.DemoApplication.start(DemoApplication.java:43)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

!ENTRY org.caleydo.core 1 0 2015-02-26 10:08:37.113
!MESSAGE Start animator

!ENTRY org.caleydo.core 1 0 2015-02-26 10:08:37.115
!MESSAGE Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]

!ENTRY org.caleydo.core.view.ViewManager@7dd611c8 1 0 2015-02-26 10:08:37.773
!MESSAGE Registering view: demo.ARcpRankTableDemoView$GLView@1aa30001

!ENTRY FilePreviewParser 1 0 2015-02-26 10:08:51.986
!MESSAGE Preview data loaded from '/Users/rbradley/buggy.txt'!

!ENTRY org.caleydo.core 1 0 2015-02-26 10:08:57.875
!MESSAGE Start animator

!ENTRY org.caleydo.core 1 0 2015-02-26 10:08:58.235
!MESSAGE Add canvas to animatorSWTGLCanvas of SWT-GLCanvas[Realized false,
    null-drawable,
    Factory   null,
    handle    0x0,
    Drawable size -1x-1,
    SWT size 0x0]

!ENTRY org.caleydo.core.view.ViewManager@7dd611c8 1 0 2015-02-26 10:08:58.239
!MESSAGE Registering view: demo.ARcpRankTableDemoView$GLView@1aa30002

```

**Comment by sgratzl** [comment]
Would you mind sending me the data /  or a similar dataset to: sgratzl@seas.harvard.edu?

**Comment by sgratzl** [comment]
I found the bug: 286c4cf4d81cd49451262a4dc2685a337dbcd5b1 and Caleydo/org.caleydo.vis.lineup.demos@c77bb824648f80acb3c4c8b49b118ac454ce3664

you numbers bust the range of float. However, LineUp is using doubles. I changed it a while a ago, but somehow missed some spots.
