### ISSUE TITLE
Entourage issue : display errir : SWT-GLCanvas[Realized true,

### ISSUE THREAD

**Issue by immuneAI** [Caleydo/caleydo#1885]
Hey guys,

I have a problem with entourage, can't visualize the pathways and getting crash. Is this problem with Java or Caleydo version. Find the error logs below,
```
eclipse.buildId=unknown
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @noDefault

This is a continuation of log file C:\Users\venkatA\.caleydo_3.1\.metadata\.bak_3.log
Created Time: 2017-08-11 11:08:25.426

org.caleydo.core.view.opengl.canvas.MyAnimator
Error
Fri Aug 11 11:49:25 AEST 2017
display error: SWT-GLCanvas[Realized true,
	jogamp.opengl.windows.wgl.WindowsOnscreenWGLDrawable,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@ca8ef3a,
	handle    0x0,
	Drawable size 3217x946,
	SWT size 3217x946]

javax.media.opengl.GLException: Caught GLException: Method "glCreateShader" not available on thread MyAnimator GL Thread
	at javax.media.opengl.GLException.newGLException(GLException.java:75)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1311)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:658)
	at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:185)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.media.opengl.GLException: Method "glCreateShader" not available
	at jogamp.opengl.gl4.GL4bcImpl.glCreateShader(GL4bcImpl.java:3437)
	at org.caleydo.core.view.opengl.layout2.util.GLGraphicsUtils.compileShader(GLGraphicsUtils.java:36)
	at org.caleydo.core.view.opengl.layout2.util.GLGraphicsUtils.loadShader(GLGraphicsUtils.java:96)
	at org.caleydo.datadomain.pathway.manager.EPathwayDatabaseType$2.call(EPathwayDatabaseType.java:83)
	at org.caleydo.datadomain.pathway.manager.EPathwayDatabaseType$2.call(EPathwayDatabaseType.java:1)
	at org.caleydo.core.view.opengl.canvas.GLContextLocal.initialValue(GLContextLocal.java:71)
	at org.caleydo.core.view.opengl.canvas.GLContextLocal.setInitialValue(GLContextLocal.java:92)
	at org.caleydo.core.view.opengl.canvas.GLContextLocal.get(GLContextLocal.java:86)
	at org.caleydo.datadomain.pathway.manager.EPathwayDatabaseType.render(EPathwayDatabaseType.java:171)
	at org.caleydo.view.pathway.v2.ui.PathwayTextureRepresentation.renderImpl(PathwayTextureRepresentation.java:117)
	at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:218)
	at org.caleydo.view.pathway.v2.ui.PathwayElement.renderImpl(PathwayElement.java:60)
	at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:218)
	at org.caleydo.core.view.opengl.layout2.GLElementDecorator.renderImpl(GLElementDecorator.java:48)
	at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:218)
	at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:298)
	at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:218)
	at org.caleydo.core.view.opengl.layout2.AGLElementView.renderPass(AGLElementView.java:263)
	at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:221)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:690)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:672)
	at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:159)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	... 12 more
```

**Comment by mstreit** [comment]
Hi @venkataddala, 

The Java version of our framework is not under active development anymore. Therefore, the libraries get outdated and make problems with current hardware and JVM versions. Sorry for not having better news for you.
