### ISSUE TITLE
Standalone fails on Windows Vista

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#325]
The message:

An error has occured. See the log file 

is displayed. This is the content of the log file:

!ENTRY org.eclipse.osgi 4 0 2009-07-14 11:15:12.408
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: Not implemented
    at org.eclipse.swt.SWT.error(SWT.java:3886)
    at org.eclipse.swt.SWT.error(SWT.java:3775)
    at org.eclipse.swt.SWT.error(SWT.java:3746)
    at org.eclipse.swt.awt.SWT_AWT.new_Frame(SWT_AWT.java:91)
    at org.caleydo.rcp.view.opengl.AGLViewPart.createPartControlGL(AGLViewPart.java:131)
    at org.caleydo.rcp.view.opengl.AGLViewPart.createGLEventListener(AGLViewPart.java:100)
    at org.caleydo.rcp.view.opengl.GLHistogramView.createPartControl(GLHistogramView.java:137)
    at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:371)
    at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:230)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
    at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2170)
    at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1065)
    at org.eclipse.ui.internal.WorkbenchPage$19.run(WorkbenchPage.java:3807)

**Comment by alexsb** [comment]
Webstart works
