### ISSUE TITLE
(seemingly random) crash upon selecting a block

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#570]
On Mac OS X this is the error message:

2011-12-08 21:34:34.795 java[4399:18803] **\* -[NSConditionLock unlock]: lock (<NSConditionLock: 0x7fd284c805b0> '(null)') unlocked when not locked
2011-12-08 21:34:34.795 java[4399:18803] **\* Break on _NSLockError() to debug.
2011-12-08 21:34:34.897 java[4399:18803] **\* -[NSConditionLock unlock]: lock (<NSConditionLock: 0x7fd284dd19b0> '(null)') unlocked when not locked
2011-12-08 21:34:34.897 java[4399:18803] **\* Break on _NSLockError() to debug.

This happens a lot when I want to select a brick for no apparent reason and it freezes the application (spinning beach ball).

**Comment by ngehlenborg** [comment]
There seems to be more to this error, namely an earlier ConcurrentModificationException:

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.898
!MESSAGE No mapping found between DataConatiners and SAMPLE for: 23

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.899
!MESSAGE No mapping found between DataConatiners and SAMPLE for: 9

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.901
!MESSAGE No mapping found between group_record_org.caleydo.datadomain.genetic_2_1604291653 and record_org.caleydo.datadomain.genetic_0_1317701801 for: 16716

!ENTRY org.eclipse.ui 4 0 2011-12-08 22:43:13.902
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.util.ConcurrentModificationException)
    at org.eclipse.swt.SWT.error(SWT.java:4282)
    at org.eclipse.swt.SWT.error(SWT.java:4197)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3935)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3612)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.caleydo.core.startup.StartupProcessor.initRCPWorkbench(StartupProcessor.java:141)
    at org.caleydo.core.startup.StartupProcessor.initStartupProcudure(StartupProcessor.java:102)
    at org.caleydo.core.startup.Application.start(Application.java:29)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
    at java.util.HashMap$EntryIterator.next(HashMap.java:834)
    at java.util.HashMap$EntryIterator.next(HashMap.java:832)
    at java.util.HashMap.putAllForCreate(HashMap.java:435)
    at java.util.HashMap.clone(HashMap.java:669)
    at org.caleydo.core.data.selection.SelectionManager.clone(SelectionManager.java:807)
    at org.caleydo.core.data.datadomain.ATableBasedDataDomain.getRecordSelectionManager(ATableBasedDataDomain.java:483)
    at org.caleydo.view.info.InfoArea.createControl(InfoArea.java:101)
    at org.caleydo.view.info.RcpInfoAreaView.createPartControl(RcpInfoAreaView.java:64)
    at org.caleydo.view.info.RcpInfoAreaView.setDataDomain(RcpInfoAreaView.java:103)
    at org.caleydo.view.info.RcpInfoAreaView.setDataDomain(RcpInfoAreaView.java:1)
    at org.caleydo.core.view.CaleydoRCPViewPart.handleSelectionUpdate(CaleydoRCPViewPart.java:364)
    at org.caleydo.core.view.listener.ExtendedSelectionUpdateListener.handleEvent(ExtendedSelectionUpdateListener.java:34)
    at org.caleydo.core.view.CaleydoRCPViewPart$1.run(CaleydoRCPViewPart.java:382)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    ... 25 more

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.904
!MESSAGE No mapping found between group_record_org.caleydo.datadomain.genetic_2_1604291653 and record_org.caleydo.datadomain.genetic_0_1317701801 for: 16716

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.906
!MESSAGE No mapping found between group_record_org.caleydo.datadomain.genetic_2_1604291653 and record_org.caleydo.datadomain.genetic_0_1317701801 for: 16716

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.909
!MESSAGE No mapping found between group_record_org.caleydo.datadomain.genetic_2_1604291653 and record_org.caleydo.datadomain.genetic_0_1317701801 for: 16716

!ENTRY IDMappingManager for SAMPLE with registered id types: [SAMPLE_2_record_org.caleydo.datadomain.generic_1_492942072, SAMPLE_2_record_org.caleydo.datadomain.genetic_1_1673013077, record_org.caleydo.datadomain.genetic_2_1604291653_2_SAMPLE, SAMPLE_2_SAMPLE_INT, SAMPLE_2_record_org.caleydo.datadomain.generic_2_295978963, record_org.caleydo.datadomain.genetic_0_1317701801_2_SAMPLE, SAMPLE_INT_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_0_1317701801, record_org.caleydo.datadomain.genetic_1_1673013077_2_SAMPLE, record_org.caleydo.datadomain.generic_1_492942072_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.generic_0_1902512020, record_org.caleydo.datadomain.generic_0_1902512020_2_SAMPLE, record_org.caleydo.datadomain.generic_2_295978963_2_SAMPLE, SAMPLE_2_record_org.caleydo.datadomain.genetic_2_1604291653] 1 0 2011-12-08 22:43:13.912
!MESSAGE No mapping found between group_record_org.caleydo.datadomain.genetic_2_1604291653 and record_org.caleydo.datadomain.genetic_0_1317701801 for: 16716
2011-12-08 22:43:14.019 java[4590:18903] **\* -[NSConditionLock unlock]: lock (<NSConditionLock: 0x7fca7e588190> '(null)') unlocked when not locked
2011-12-08 22:43:14.020 java[4590:18903] **\* Break on _NSLockError() to debug.
2011-12-08 22:43:14.121 java[4590:18903] **\* -[NSConditionLock unlock]: lock (<NSConditionLock: 0x7fca7e587600> '(null)') unlocked when not locked
2011-12-08 22:43:14.121 java[4590:18903] **\* Break on _NSLockError() to debug.
