### ISSUE TITLE
Webstart on Mac hangs up after loading data before GL views get initialized

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#754]
The freeze occures also when loading sample project or sample gene expression.

Christian, could you please look into that and try if you can reproduce the problem on the ICG Mac?
We would like to show the new TCGA integration tomorrow at the Broad. It would be great if Mike Noble (the Firehose Coordinator) could start the cal files on his Mac.

The webstart workstation used to work on Nils' PC before our last release of 2.0.2 the day before yesterday.

**Comment by mstreit** [comment]
Nils still encounters freezes. This time not during the startup but when a new view is created in StratomeX after selecting a brick - only sometimes of course.

Log:

"AWT-AppKit" daemon prio=6 tid=7fdc0a10c000 nid=0x7fff76fef960 waiting for monitor entry [7fff6e178000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at java.awt.Component.getGraphicsConfiguration(Component.java:1065)
    - waiting to lock <7c04ef850> (a java.awt.Component$AWTTreeLock)
    at javax.media.opengl.awt.GLCanvas.<init>(GLCanvas.java:236)
    at javax.media.opengl.awt.GLCanvas.<init>(GLCanvas.java:179)
    at org.caleydo.core.view.ARcpGLViewPart.createGLCanvas(ARcpGLViewPart.java:63)
    at org.caleydo.view.histogram.RcpGLHistogramView.createPartControl(RcpGLHistogramView.java:84)
    at org.caleydo.view.info.dataset.RcpDatasetInfoView.createPartControl(RcpDatasetInfoView.java:156)
    at org.caleydo.view.info.dataset.RcpDatasetInfoView.setDataDomain(RcpDatasetInfoView.java:191)
    at org.caleydo.view.info.dataset.RcpDatasetInfoView.setDataDomain(RcpDatasetInfoView.java:1)
    at org.caleydo.core.view.CaleydoRCPViewPart.handleSelectionUpdate(CaleydoRCPViewPart.java:428)
    at org.caleydo.core.view.listener.ExtendedSelectionUpdateListener.handleEvent(ExtendedSelectionUpdateListener.java:58)
    at org.caleydo.core.view.CaleydoRCPViewPart$1.run(CaleydoRCPViewPart.java:444)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    - locked <7baf8d6a0> (a org.eclipse.swt.widgets.RunnableLock)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3938)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3615)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.caleydo.core.startup.StartupProcessor.initRCPWorkbench(StartupProcessor.java:226)
    at org.caleydo.core.startup.StartupProcessor.initStartupProcudure(StartupProcessor.java:93)
    at org.caleydo.core.startup.Application.start(Application.java:44)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.WebStartMain.basicRun(WebStartMain.java:79)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.WebStartMain.main(WebStartMain.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.javaws.Launcher.invokeMainMethod(Launcher.java:1926)

   Locked ownable synchronizers:
    - None
