### ISSUE TITLE
Caleydo does not work on Mac Mountain Lion

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#798]
Seems to be a JOGL bug that has not been fixed yet
http://forum.jogamp.org/JOGL-on-Mac-OSX-libjogl-desktop-jnilib-error-td4025842.html

Jogl has fixed this in builds, but is not in rc 10 so far. Waiting for rc 11.

**Comment by mstreit** [comment]
rc11 is out since nov. last year and already part of Caleydo. the problem should be fixed by now. reopen if problem occurs again.

**Comment by dputhier** [comment]
Hi,
I'm trying to install Caleydo on my Mac. Unfortunately I ran with an issue related to "org.caleydo.rcp.application". You will find below some information related to my system and the error message I got from the log file ("Caleydo.app/configuration/1430321625682.log"). Do you have any idea ?
Thank you in advance
Best

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10
BuildVersion:	14A389a

$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

$ cat Caleydo.app/configuration/1430321625682.log
.....
!ENTRY org.eclipse.osgi 4 0 2015-04-29 17:33:47.019
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.caleydo.rcp.application" could not be found in the registry. The applications available are: org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
