### ISSUE TITLE
PRAD tumor type 09_13_2012 run has a dataset where minimum is 1328 and maximum is 0

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#840]
Exception thrown during cal project generation when normalizing the dataset:

java.lang.IllegalArgumentException: Minimum (1328.0) was bigger as maximum (0.0) for: 
[F@62918c34
    at org.caleydo.core.util.conversion.ConversionTools.normalize(ConversionTools.java:113)
    at org.caleydo.core.data.collection.container.FloatContainer.normalize(FloatContainer.java:109)

**Comment by mstreit** [comment]
Fixed with R5414
Allowed min to be equal to max in input data, which doesn't make much sense, but avoids problems in some sparse datsets.

**Comment by mstreit** [comment]
Still the same error
