### ISSUE TITLE
Workspace saved in project can not be re-opened.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#859]
In stable branch. An error dialog pops up. Can be observed using the current sample project.
{{{
org.eclipse.core.runtime.AssertionFailedException: null argument:The dialog should be created in UI thread
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.jface.dialogs.IconAndMessageDialog.getSWTImage(IconAndMessageDialog.java:282)
    at org.eclipse.jface.dialogs.IconAndMessageDialog.getErrorImage(IconAndMessageDialog.java:233)
    at org.eclipse.jface.dialogs.MessageDialog.<init>(MessageDialog.java:179)
    at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:360)
    at org.eclipse.jface.dialogs.MessageDialog.openError(MessageDialog.java:431)
    at org.eclipse.ui.internal.Workbench$54.run(Workbench.java:2108)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench.restoreState(Workbench.java:2088)
    at org.eclipse.ui.internal.WorkbenchConfigurer.restoreState(WorkbenchConfigurer.java:183)
    at org.eclipse.ui.application.WorkbenchAdvisor$1.run(WorkbenchAdvisor.java:781)

!ENTRY org.caleydo.core.startup.SerializationStartupProcedure@7935c7b0 1 0 2012-11-15 15:10:40.153
}}}

**Comment by sgratzl** [comment]
r5633 (fixing sample project and project saver)

revert: r5481

**Comment by mstreit** [comment]
r5633
supported workbench ID != caleydo ID
