### ISSUE TITLE
TourGuide causes NPE during project deserialization

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#917]
For now, it is ok when the data of the tour guide is not serialized. The view can be freshly initialized when restored.

NPE:
{{{
java.lang.NullPointerException
    at org.caleydo.view.tourguide.RcpGLTourGuideView$1.partActivated(RcpGLTourGuideView.java:136)
    at org.caleydo.view.tourguide.RcpGLTourGuideView.createPartControl(RcpGLTourGuideView.java:76)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:129)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
}}}

**Comment by sgratzl** [comment]
r5672 that partical npe should not longer occur
